"""The JavaScript writer must keep agreeing with the Python one.

`web/src/make3mf.js` is a port of `prep/write3mf.py`, and a port is a second
copy of knowledge that was expensive to acquire -- the production extension, the
cover-thumbnail relationships, the row-vector transform, the 487 settings. Two
copies drift. When they do, the browser will quietly start writing a container
nobody has ever uploaded, and the only symptom will be MakerWorld saying no to a
user who is not in the room.

So this feeds both writers identical geometry and diffs the result. Random
UUIDs are normalised away; the pictures are not compared, because a canvas and
a numpy rasteriser will never agree on pixels and are not supposed to.

Needs Node, and skips without it rather than failing -- the port is not what
most work on this repo touches.
"""

from __future__ import annotations

import json
import re
import shutil
import subprocess
import zipfile
from pathlib import Path

import numpy as np
import pytest
import trimesh

from prep.profiles import load_printer
from prep.write3mf import place_on_bed, write_project_3mf

ROOT = Path(__file__).resolve().parent.parent
HARNESS = ROOT / "spikes" / "web3mf_compare.mjs"
PROFILES = ROOT / "web" / "src" / "data" / "printers.json"
PRINTER = "Bambu Lab P1S 0.4 nozzle"

pytestmark = pytest.mark.skipif(
    shutil.which("node") is None or not HARNESS.is_file(),
    reason="needs Node and spikes/web3mf_compare.mjs",
)

_UUID = re.compile(rb'p:UUID="[^"]*"')
_normalise = lambda raw: _UUID.sub(b'p:UUID="X"', raw)   # noqa: E731


@pytest.fixture(scope="module")
def both(tmp_path_factory):
    """The same box written by each side."""
    out = tmp_path_factory.mktemp("web3mf")
    mesh = trimesh.creation.box(extents=(40, 30, 20))
    printer = load_printer(PRINTER)

    python_3mf = out / "python.3mf"
    write_project_3mf(python_3mf, mesh, printer, title="box.stl")

    # Hand the port the *same* vertices, in the same order. Rebuilding the box
    # in JavaScript would differ in vertex ordering and fill the diff with noise
    # that says nothing about the writer.
    matrix = place_on_bed(mesh, printer, None)
    (out / "mesh.json").write_text(json.dumps({
        "printer": printer.name,
        "material": "PLA",
        "title": "box.stl",
        "vertices": [float(v) for v in np.asarray(mesh.vertices, float).reshape(-1)],
        "triangles": [int(v) for v in np.asarray(mesh.faces, int).reshape(-1)],
        "matrix": [[float(x) for x in row] for row in matrix],
    }), encoding="utf-8")

    js_3mf = out / "javascript.3mf"
    result = subprocess.run(
        ["node", str(HARNESS), str(out / "mesh.json"), str(js_3mf)],
        cwd=ROOT, capture_output=True, text=True, timeout=180)
    assert result.returncode == 0, result.stderr

    return zipfile.ZipFile(python_3mf), zipfile.ZipFile(js_3mf)


def test_the_baked_profiles_exist_and_carry_every_printer():
    """web/src/data/printers.json is generated by spikes/export_web_profiles.py.
    Stale or missing, the browser writes settings that do not match the server."""
    assert PROFILES.is_file(), "run spikes/export_web_profiles.py"
    data = json.loads(PROFILES.read_text(encoding="utf-8"))
    assert len(data["printers"]) >= 7
    assert all(p["materials"] for p in data["printers"])


def test_both_writers_produce_the_same_members(both):
    python_zip, js_zip = both
    assert set(python_zip.namelist()) == set(js_zip.namelist())
    assert len(js_zip.namelist()) == 15


@pytest.mark.parametrize("member", [
    "[Content_Types].xml",
    "_rels/.rels",
    "3D/_rels/3dmodel.model.rels",
    "Metadata/slice_info.config",
    "Metadata/cut_information.xml",
    "Metadata/filament_sequence.json",
    "Metadata/model_settings.config",
])
def test_the_fixed_members_are_byte_identical(both, member):
    python_zip, js_zip = both
    assert python_zip.read(member) == js_zip.read(member)


def test_the_settings_blob_is_byte_identical(both):
    """487 keys, in the same order, with the same formatting. The order matters
    only because it makes drift visible; it is why the export does not sort."""
    python_zip, js_zip = both
    assert python_zip.read("Metadata/project_settings.config") == \
        js_zip.read("Metadata/project_settings.config")


@pytest.mark.parametrize("member", ["3D/3dmodel.model",
                                    "3D/Objects/object_1.model"])
def test_the_model_xml_differs_only_by_its_random_uuids(both, member):
    python_zip, js_zip = both
    assert _normalise(python_zip.read(member)) == _normalise(js_zip.read(member))


def test_the_build_transform_survives_the_port(both):
    """The row-vector transpose. Bounding boxes cannot see this one -- getting
    it backwards prints mirrored with nothing downstream to catch it."""
    python_zip, js_zip = both
    grab = lambda z: re.search(                                    # noqa: E731
        r'<item[^>]*transform="([^"]+)"', z.read("3D/3dmodel.model").decode()).group(1)
    assert grab(python_zip) == grab(js_zip)


def test_an_independent_reader_gets_the_same_geometry_from_each(both):
    python_zip, js_zip = both
    sizes = []
    for z in (python_zip, js_zip):
        mesh = trimesh.load(z.filename, force="mesh")
        sizes.append((len(mesh.faces), tuple(np.round(mesh.extents, 3)),
                      round(float(mesh.bounds[0][2]), 3)))
    assert sizes[0] == sizes[1]
    assert sizes[1][2] == 0.0                    # sitting on the plate


def test_the_pictures_are_the_sizes_bambu_writes(both):
    """Content is not compared -- a canvas and a numpy rasteriser will never
    agree on pixels -- but the dimensions are part of the container's shape."""
    import struct
    _, js_zip = both
    expected = {
        "Metadata/plate_1.png": (512, 512),
        "Metadata/plate_1_small.png": (128, 128),
        "Metadata/plate_no_light_1.png": (512, 512),
        "Metadata/top_1.png": (512, 512),
        "Metadata/pick_1.png": (512, 512),
    }
    for name, size in expected.items():
        raw = js_zip.read(name)
        assert raw[:8] == b"\x89PNG\r\n\x1a\n"
        assert struct.unpack(">II", raw[16:24]) == size
