"""Re-write a project 3mf through Bambu Studio itself.

MakerWorld validates uploads harder than Bambu Studio does. Our own container
opens correctly in Bambu Studio -- geometry, settings and supports all intact --
but MakerWorld's upload form rejects it with:

    "The 3mf file is not generated by Bambu Studio, or the printer selected
     in the 3mf is not a Bambu Lab printer."

Round-tripping the same file through ``bambu-studio.exe --export-3mf`` produces
a container MakerWorld accepts, with our geometry, orientation, scale and
settings preserved. This is exactly the fallback spec §2A reserved: run Bambu
Studio "purely as a 3mf *writer*, not a slicer".

Note what this does **not** do: no slicing. The exported project carries no
G-code, so MakerWorld still re-slices against whatever printer and filament the
user picks at print time, and §2A's "do not pre-slice" design holds.

The dependency is real and worth stating plainly: any host that needs
MakerWorld-ready output needs Bambu Studio installed. Matching its container
format in our own writer would remove that, and is the better long-term answer;
see docs/transport-findings.md.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import tempfile
import zipfile
from pathlib import Path

# Where Bambu Studio installs. Override with PREP_BAMBU_STUDIO.
DEFAULT_PATHS = [
    Path(r"C:/Program Files/Bambu Studio/bambu-studio.exe"),
    Path(r"C:/Program Files (x86)/Bambu Studio/bambu-studio.exe"),
    Path("/usr/bin/bambu-studio"),
    Path("/opt/BambuStudio/bambu-studio"),
]

EXPORT_TIMEOUT_S = 600

# Bambu Studio renders these into the exported project. plate_1.png is the lit
# 512x512 plate view -- the same picture a person would otherwise screenshot.
PREVIEW_MEMBERS = ("Metadata/plate_1.png", "Metadata/top_1.png",
                   "Metadata/plate_no_light_1.png")


class BambuStudioUnavailable(RuntimeError):
    """Bambu Studio is not installed, so MakerWorld-ready output is not possible."""


class ExportFailed(RuntimeError):
    """Bambu Studio ran but produced nothing usable."""


def find_bambu_studio() -> Path | None:
    env = os.environ.get("PREP_BAMBU_STUDIO")
    if env:
        candidate = Path(env)
        return candidate if candidate.is_file() else None
    for path in DEFAULT_PATHS:
        if path.is_file():
            return path
    return None


def available() -> bool:
    return find_bambu_studio() is not None


def rewrite_for_makerworld(path, *, exe: Path | None = None,
                           timeout: int = EXPORT_TIMEOUT_S) -> Path:
    """Rewrite ``path`` in place through Bambu Studio. Returns the same path.

    Bambu Studio is GUI-subsystem and prints nothing to a console, so success is
    judged by the file it writes rather than by its output.
    """
    path = Path(path)
    exe = exe or find_bambu_studio()
    if exe is None:
        raise BambuStudioUnavailable(
            "Bambu Studio isn't installed, so I can't produce a file MakerWorld "
            "will accept. Set PREP_BAMBU_STUDIO to its executable if it's "
            "somewhere unusual."
        )

    with tempfile.TemporaryDirectory(prefix="prep-mw-") as tmp:
        out_dir = Path(tmp)
        proc = subprocess.run(
            [str(exe), "--export-3mf", "exported.3mf",
             "--outputdir", str(out_dir), str(path)],
            capture_output=True, timeout=timeout,
        )
        exported = out_dir / "exported.3mf"
        if not exported.is_file():
            detail = (proc.stderr or proc.stdout or b"").decode("utf-8", "replace").strip()
            raise ExportFailed(
                f"Bambu Studio did not export a file{': ' + detail[:200] if detail else ''}"
            )
        shutil.copyfile(exported, path)

    return path


def extract_preview(path, dest=None) -> Path | None:
    """Pull the plate render out of a project 3mf and save it beside the file.

    MakerWorld requires a gallery image at upload, and on a private model a
    render is accepted (verified 2026-08-23) -- so handing the user a ready-made
    picture removes a step from §6.5's handoff that they would otherwise satisfy
    by screenshotting the slicer.
    """
    path = Path(path)
    dest = Path(dest) if dest else path.with_name(path.stem + "-preview.png")

    with zipfile.ZipFile(path) as z:
        names = set(z.namelist())
        for member in PREVIEW_MEMBERS:
            if member in names:
                dest.write_bytes(z.read(member))
                return dest
    return None
