/**
 * The pages a search engine can actually read.
 *
 * The app is a React page with an empty <div id="root"> in the HTML. Google
 * will render it eventually; the crawlers behind AI answers -- GPTBot,
 * ClaudeBot, PerplexityBot, OAI-SearchBot -- fetch the HTML and stop. To all of
 * them the product was a blank page titled "Handoff3D", which is a word nobody
 * types into a search box. These are static files with the answer written out
 * in the HTML, one page per question people actually ask.
 *
 * They are plain files in web/public/, not Vite entry points, deliberately:
 * nothing here needs bundling, and a page that must survive with JavaScript
 * switched off should not go through a JavaScript build to get there. Vercel
 * copies public/ to the site root, and `cleanUrls` in vercel.json serves them
 * without the .html. The filesystem is checked before the catch-all rewrite, so
 * they win over it without needing a rewrite of their own.
 *
 * ONE DELIBERATE BREAK WITH THE COPY RULES. Section 6 of the spec bans mesh,
 * manifold, normals, infill, gcode and slice from user-facing strings, and
 * every string in the app obeys it. These pages cannot: "slice" and "STL" are
 * the words people type, and a page that avoids them cannot be found by anyone
 * searching for them. So the jargon appears where it is the question, and the
 * answer under it is in plain words. Nothing in web/src/ is affected.
 *
 * Sources stay ASCII and typography goes in as entities, same as handoff.js.
 * Generated by build-guides.mjs; the output is committed, and
 * tests/test_guides.py fails if the two have drifted.
 */

export const SITE = 'https://bambu-print-prep.vercel.app'
export const BRAND = 'Handoff3D'

/**
 * The share picture. No render was commissioned for this -- the app icon is
 * real, square and already in the repo, and a square og:image is better than
 * the grey box a link with none at all gets.
 */
export const OG_IMAGE = '/icons/icon-512.png'

/**
 * Every Bambu machine the printer picker knows, for the pages that list them.
 * Written out rather than read from printers.json: these are static files, and
 * a generator that reached into the profile index would leave the committed
 * pages stale the moment the index changed without anything saying so.
 * tests/test_guides.py checks this list against printers.json instead, which
 * fails loudly in the direction that matters.
 */
export const MODELS = [
  'A1 mini', 'A1', 'P1P', 'P1S', 'P2S', 'X1', 'X1 Carbon', 'X1E', 'X2D',
  'A2L', 'H2C', 'H2S', 'H2D', 'H2D Pro',
]

const CSS = `
:root { color-scheme: light dark;
        --ink: #1a1a1a; --dim: #5b5b5b; --bg: #fbfaf8; --card: #fff;
        --line: #e5e2dc; --accent: #17663f; }
@media (prefers-color-scheme: dark) {
  :root { --ink: #ececec; --dim: #a6a6a6; --bg: #17181a; --card: #212327;
          --line: #34363b; --accent: #6fd39b; } }
* { box-sizing: border-box; }
body { margin: 0; padding: 0 5vw 14vw; background: var(--bg); color: var(--ink);
       font: 400 18px/1.62 -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
       -webkit-text-size-adjust: 100%; }
main, header, footer { max-width: 38rem; margin: 0 auto; }
header { padding: 1.6rem 0 .4rem; }
header a.home { color: var(--dim); text-decoration: none; font-size: .93rem; }
header a.home b { color: var(--ink); }
h1 { font-size: 1.95rem; line-height: 1.18; margin: 1.2rem 0 .6rem;
     letter-spacing: -.015em; }
h2 { font-size: 1.22rem; line-height: 1.3; margin: 2.3rem 0 .5rem; }
h3 { font-size: 1.02rem; margin: 1.5rem 0 .3rem; }
p { margin: 0 0 1rem; }
.lede { font-size: 1.12rem; margin-bottom: 1.6rem; }
ul, ol { margin: 0 0 1.1rem; padding-left: 1.3rem; }
li { margin: 0 0 .45rem; }
a { color: var(--accent); }
b { font-weight: 650; }
.cta { display: block; background: var(--accent); color: var(--bg);
       text-decoration: none; text-align: center; font-weight: 650;
       padding: .95rem 1.2rem; border-radius: 13px; margin: 2rem 0 .6rem; }
.cta-sub { text-align: center; color: var(--dim); font-size: .9rem;
           margin: 0 0 2rem; }
.card { background: var(--card); border: 1px solid var(--line);
        border-radius: 14px; padding: 1.1rem 1.25rem; margin: 0 0 1.4rem; }
.card p:last-child { margin-bottom: 0; }
code { font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
       font-size: .92em; background: var(--card); border: 1px solid var(--line);
       border-radius: 5px; padding: .08em .35em; }
/* The bed table is the one thing here wider than a phone. It scrolls inside
   its own box rather than making the whole page scroll sideways. */
.scroll { overflow-x: auto; margin: 0 0 1.2rem; }
table { border-collapse: collapse; width: 100%; min-width: 21rem;
        font-size: .95rem; }
th, td { text-align: left; padding: .5rem .7rem; border-bottom: 1px solid var(--line); }
th { font-weight: 650; }
td:last-child { white-space: nowrap; color: var(--dim); }
/* The comparison table's last column is an answer, not an aside: it needs the
   full ink and it needs to wrap, or a three-column table of sentences is a
   pale strip running off the side of a phone. */
table.compare td:last-child { white-space: normal; color: inherit; }
footer { border-top: 1px solid var(--line); margin-top: 3rem; padding-top: 1.4rem;
         color: var(--dim); font-size: .93rem; }
footer ul { list-style: none; padding: 0; }
`

/** Python's html.escape(s, quote=True), character for character. */
export function escape(text) {
  return String(text)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#x27;')
}

/** Sources stay ASCII; the page should still read like typography. */
const dashes = (text) => text.split(' -- ').join(' &mdash; ')

/**
 * The pages. Each is a question somebody types, answered in the first
 * paragraph, because that paragraph is what an answer engine quotes.
 *
 * HALF THESE FIELDS ARE ESCAPED AND HALF ARE RAW HTML, and nothing about a
 * string says which it is, so it is written down here:
 *
 *   escaped     title, description, h1, section headings, faq questions.
 *               Write them as plain text. An entity in one of these comes out
 *               visible, because `escape` turns its `&` into `&amp;` -- which
 *               is how a heading shipped reading `What &quot;too big&quot;
 *               means`. Type the quote or the apostrophe itself and let
 *               `escape` do it.
 *   raw HTML    lede, section bodies, faq answers. These carry their own tags
 *               and their own entities, and are passed through untouched
 *               apart from `dashes`. A bare `&` or `<` in one of these is a
 *               bug in the other direction.
 *
 * faq answers are the one field read twice -- into the page as HTML, and into
 * the JSON-LD through JSON.stringify, which does not know what an entity is.
 * So an entity there would come out literal in the structured data even while
 * the visible page looked right. Keep them plain prose: no tags, no entities.
 *
 * tests/test_guides.py fails on any `&amp;` followed by an entity name, which
 * is the signature of the first mistake wherever it happens.
 */
export const PAGES = [
  {
    slug: 'bambu-studio-on-ipad',
    title: 'Bambu Studio on iPad: what works, what does not',
    description:
      'Bambu Studio has no iPad version and Apple will not run one. Here is '
      + 'what you can do instead, in Safari, to get a print-ready file for a '
      + 'Bambu Lab printer without a computer.',
    h1: 'Bambu Studio on iPad',
    lede:
      '<b>There is no iPad version of Bambu Studio, and there is not going to '
      + 'be one soon.</b> Bambu Studio is a desktop program for Windows, macOS '
      + 'and Linux. It is not on the App Store, iPadOS will not run a Windows '
      + 'or macOS program, and no setting or workaround changes that. What you '
      + 'can do is prepare the file somewhere else and send it to the printer '
      + 'from your iPad -- that part works, and it works today.',
    sections: [
      ['Why it cannot simply be ported', [
        '<p>Bambu Studio is built on the same foundations as PrusaSlicer and '
        + 'OrcaSlicer: a large C++ desktop application with a desktop windowing '
        + 'toolkit under it. Getting that onto iPadOS is not a recompile, it is '
        + 'a rewrite of the entire interface, and it would still have to pass '
        + 'App Store review as a new app.</p>',
        '<p>People sometimes suggest running it in a remote desktop session '
        + 'against a PC at home. That does work, and if you already have a PC '
        + 'sitting there it is a fine answer. It is not an answer if the iPad '
        + '<i>is</i> the computer.</p>',
      ]],
      ['What an iPad can actually do', [
        '<p>Two things have to happen between a downloaded model and a printed '
        + 'object. The first is preparing it: getting it the right size, the '
        + 'right way up, and turned into a file the printer understands. The '
        + 'second is sending it to the machine.</p>',
        '<p>Sending it has always been possible from an iPad -- the Bambu Handy '
        + 'app does it. It was the first half that had no answer, and that is '
        + 'the half this page is about. <b>' + BRAND + ' does the preparing in '
        + 'Safari itself.</b> You open a web page, choose your model, pick your '
        + 'printer and your size, and it writes a finished Bambu project file '
        + 'straight into your Files app.</p>',
        '<p>It is free, there is no account, and your model is not uploaded '
        + 'anywhere -- the work happens on the iPad, inside the browser tab.</p>',
      ]],
      ['Which printers it covers', [
        '<p>Every current Bambu Lab machine, with the bed size and the print '
        + 'settings taken from Bambu Studio&#x27;s own profiles rather than '
        + 'guessed at: ' + MODELS.join(', ') + '. Each of them in 0.2, 0.4, 0.6 '
        + 'and 0.8&nbsp;mm nozzle versions, because on a Bambu machine the '
        + 'nozzle is effectively a different printer, with its own layer '
        + 'heights and its own line widths.</p>',
      ]],
      ['What you still need Bambu Studio for', [
        '<p>Plenty, and it is worth being straight about it. Supports placed by '
        + 'hand, painted-on settings, multi-colour assignment, custom filament '
        + 'profiles, tuning towers, changing anything about how the printer '
        + 'moves -- all of that is desktop work. If you have a computer, use '
        + 'Bambu Studio. It is free, and it is better at its job than any web '
        + 'page.</p>',
        '<p>What is covered here is the common case: a model somebody else '
        + 'designed, printed at a sensible size on standard settings. That is '
        + 'most prints, and it was the case with no iPad answer at all.</p>',
      ]],
    ],
    faq: [
      ['Is there a Bambu Studio app for iPad?',
        'No. Bambu Studio is a desktop application for Windows, macOS and '
        + 'Linux, and there is no iPadOS version on the App Store. Bambu Lab '
        + 'publishes Bambu Handy for iOS and iPadOS, but Handy sends and '
        + 'monitors prints -- it does not prepare a model.'],
      ['Can I run Bambu Studio on an iPad some other way?',
        'Only by remote-controlling a computer that is already running it, '
        + 'through a remote desktop app. There is no way to run it on the iPad '
        + 'itself.'],
      ['Can I prepare a model for a Bambu printer without any computer?',
        'Yes. Handoff3D runs in Safari on an iPad and writes a print-ready '
        + 'Bambu project file into the Files app. Bambu Handy then sends it to '
        + 'the printer.'],
    ],
  },

  {
    slug: 'resize-a-model-on-ipad',
    title: 'How to resize an STL or 3MF on an iPad',
    description:
      'Scale a downloaded 3D model to the size you want on an iPad, in Safari, '
      + 'and save a print-ready file for a Bambu Lab printer. No app, no '
      + 'account, nothing uploaded.',
    h1: 'How to resize a model on an iPad',
    lede:
      'You can resize a downloaded model on an iPad without installing '
      + 'anything: open <a href="/">' + BRAND + '</a> in Safari, choose the '
      + 'file, and type the size you want in millimetres. It shows you the '
      + 'model at that size on your printer&#x27;s own bed and saves a '
      + 'print-ready file into Files. The whole thing happens in the browser '
      + 'tab -- your model is never uploaded.',
    sections: [
      ['Step by step', [
        '<ol>'
        + '<li><b>Get the file onto the iPad.</b> Downloading from MakerWorld, '
        + 'Printables or Thingiverse in Safari puts it in Files, under '
        + 'Downloads.</li>'
        + '<li><b>Open the page and tap Choose a model.</b> iOS offers Photo '
        + 'Library and Take Photo first -- you want <b>Choose File</b>, the '
        + 'third row down.</li>'
        + '<li><b>Pick your printer.</b> The bed drawn underneath the model '
        + 'changes to match, so you can see immediately whether the thing '
        + 'fits.</li>'
        + '<li><b>Set the size.</b> Type a measurement in millimetres, or drag '
        + 'the slider. Across, deep and tall are all shown, so you can size by '
        + 'whichever one matters -- the height of a figure, the width of a '
        + 'bracket, the diameter of a lid.</li>'
        + '<li><b>Save it.</b> Out comes a Bambu project file, and a page of '
        + 'instructions for getting it to the printer.</li>'
        + '</ol>',
      ]],
      ['Size by the measurement that matters, not by percent', [
        '<p>Most resizing goes wrong because it is done as a percentage. '
        + '&quot;Scale to 140%&quot; tells you nothing about whether the result '
        + 'fits the shelf. Here you give the real measurement, in millimetres, '
        + 'and the other two directions follow proportionally.</p>',
        '<p>One thing worth knowing if your model arrived tipped or lying on '
        + 'its side: the sizes are measured against the model as it will stand '
        + 'on the plate, not against however the file happened to be saved. So '
        + '&quot;tall&quot; is the height it will actually print at.</p>',
      ]],
      ['If it is too big for the bed', [
        '<p>Scaling down is not the only way out. A model larger than your bed '
        + 'can be cut up and spread over as many plates as it needs, then '
        + 'printed in pieces -- see <a href="/split-a-model-too-big-for-your-'
        + 'bed">when a model is too big for the bed</a>.</p>',
      ]],
      ['Which files it will open', [
        '<p>STL, 3MF, OBJ and PLY -- the four formats models are actually '
        + 'published in. A 3MF exported by Bambu Studio or OrcaSlicer opens '
        + 'fine.</p>',
      ]],
    ],
    faq: [
      ['How do I scale an STL on an iPad?',
        'Open Handoff3D in Safari, choose the STL from your Files app, and '
        + 'enter the size you want in millimetres. It writes a resized, '
        + 'print-ready file back into Files. Nothing is installed and the model '
        + 'is not uploaded.'],
      ['Can I resize a 3MF without a computer?',
        'Yes. 3MF is one of the four formats it reads, alongside STL, OBJ and '
        + 'PLY, and the file it writes back out is a Bambu project file.'],
      ['Does resizing in a browser lose quality?',
        'No. Scaling a model is arithmetic on its coordinates. The shape is '
        + 'described mathematically, so it comes out as the same shape at a '
        + 'different size, with nothing thrown away.'],
    ],
  },

  {
    slug: '3d-print-from-ipad',
    title: '3D printing from an iPad, with no computer at all',
    description:
      'The complete route from a downloaded model to a finished print using '
      + 'only an iPad or iPhone and a Bambu Lab printer. Free, no account, '
      + 'nothing uploaded.',
    h1: '3D printing from an iPad, with no computer',
    lede:
      'It is possible to go from a model you downloaded to an object on the '
      + 'plate using nothing but an iPad and a Bambu Lab printer. The step that '
      + 'used to need a desktop -- preparing the file -- now runs in Safari. '
      + 'The step after it, sending the file to the machine, has always been '
      + 'possible through Bambu Handy. This page is the whole route, end to '
      + 'end.',
    sections: [
      ['The three things that have to happen', [
        '<p><b>1. Find a model.</b> MakerWorld, Printables and Thingiverse all '
        + 'work in Safari. A download lands in Files, under Downloads.</p>',
        '<p><b>2. Prepare it.</b> Size it, stand it the right way up, and turn '
        + 'it into a file your printer understands. This is the part that used '
        + 'to need Bambu Studio on a desktop. <a href="/">' + BRAND + '</a> '
        + 'does it in the browser.</p>',
        '<p><b>3. Send it.</b> Bambu does not let other apps talk to your '
        + 'printer directly, so the file goes up to your own private page on '
        + 'MakerWorld, and Bambu Handy prints it from there. It is a handful of '
        + 'taps, once per model.</p>',
      ]],
      ['Why step three is clunky, and why it is not your fault', [
        '<p>There is no public way for a third-party app to hand a file to a '
        + 'Bambu printer. The machine takes work from Bambu&#x27;s own '
        + 'software, and from Bambu&#x27;s own cloud. So the file travels: iPad '
        + '&rarr; your private MakerWorld page &rarr; Bambu Handy &rarr; '
        + 'printer. Set the model to <b>Private</b> when you upload it and '
        + 'nobody else ever sees it.</p>',
        '<p>Every file comes with a page of these steps saved next to it, '
        + 'because there are several places to get lost and you will want it '
        + 'again next time. The steps are written out on '
        + '<a href="/how-to-print-from-an-ipad">getting the file to the '
        + 'printer</a>.</p>',
      ]],
      ['Does it work on an iPhone?', [
        '<p>Yes. It is the same page and the same route. An iPad is more '
        + 'comfortable for judging size on the bed, but nothing here needs the '
        + 'bigger screen.</p>',
      ]],
      ['What it costs', [
        '<p>Nothing. There is no account, no sign-in, and no upload of your '
        + 'model. Visits are counted anonymously, so it is possible to tell '
        + 'whether anybody is finding it; the model, its name and everything '
        + 'measured from it stay on your device.</p>',
      ]],
    ],
    faq: [
      ['Can you 3D print from an iPad without a computer?',
        'Yes, with a Bambu Lab printer. Prepare the file in Safari with '
        + 'Handoff3D, upload it as a private model on MakerWorld, and print it '
        + 'from the Bambu Handy app. No desktop computer is involved at any '
        + 'point.'],
      ['Does it work on an iPhone as well as an iPad?',
        'Yes. The same page works on an iPhone, and the steps are identical.'],
      ['Can Bambu Handy prepare a model on its own?',
        'No. Bambu Handy sends and monitors prints and browses MakerWorld. It '
        + 'cannot take a downloaded model and turn it into something printable '
        + '-- that is the gap this fills.'],
    ],
  },

  {
    slug: 'split-a-model-too-big-for-your-bed',
    title: 'Splitting a model too big for your printer bed, on an iPad',
    description:
      'Cut an oversized model into pieces and spread them across as many build '
      + 'plates as it takes, on an iPad, with no desktop slicer.',
    h1: 'When a model is too big for the bed',
    lede:
      'A model larger than your build plate does not have to be shrunk. It can '
      + 'be cut into pieces, laid out across as many plates as it needs, and '
      + 'printed in batches -- and <a href="/">' + BRAND + '</a> does that on '
      + 'an iPad, in Safari. You get one file containing every plate, in '
      + 'order.',
    sections: [
      ['What "too big" means on each machine', [
        '<p>Bed sizes vary more than people expect. An A1 mini gives you '
        + '180&nbsp;&times;&nbsp;180&nbsp;&times;&nbsp;180&nbsp;mm. A P1S, an '
        + 'X1 Carbon or an A1 gives you roughly 256&nbsp;mm in each direction. '
        + 'The H2D and H2S are larger again, around '
        + '350&nbsp;&times;&nbsp;320&nbsp;&times;&nbsp;325&nbsp;mm. Pick your '
        + 'printer and the plate drawn under the model is the real one, so it '
        + 'is obvious at a glance whether you have a problem.</p>',
      ]],
      ['Three ways out, in the order worth trying', [
        '<h3>Print it smaller</h3>'
        + '<p>Often the right answer, and always the least work. Type the size '
        + 'you want and look at it on the plate.</p>'
        + '<h3>Stand it differently</h3>'
        + '<p>A long, flat model that will not fit across the bed may fit '
        + 'diagonally, or standing on its end. The height of a Bambu bed is '
        + 'roughly the same as its width, so tipping something upright can buy '
        + 'a surprising amount of room.</p>'
        + '<h3>Cut it up</h3>'
        + '<p>For anything genuinely large this is the answer, and it is what '
        + 'people do for helmets, vases, statues and terrain. The pieces are '
        + 'laid out over several plates, and you print one plate at a time and '
        + 'glue the results.</p>',
      ]],
      ['Models that arrive already in pieces', [
        '<p>Many large models are published as a set of parts inside one file. '
        + 'Those are recognised as separate pieces, each stood up the best way '
        + 'for itself, and then arranged across plates -- so a file with '
        + 'fourteen parts in it does not become one impossible object.</p>',
      ]],
      ['Flattening a curved bottom', [
        '<p>A related problem: a model that was sculpted rather than designed '
        + 'often has no flat face to sit on, and printing it as it comes means '
        + 'either a large support structure or a poor first layer. You can take '
        + 'a slice off the bottom to give it a flat face to stand on, choosing '
        + 'how deep to cut and watching the footprint appear as you do.</p>',
      ]],
    ],
    faq: [
      ['How do I print something bigger than my Bambu printer bed?',
        'Cut it into pieces, print them across several plates, and glue them '
        + 'together. Handoff3D does the cutting and the plate layout on an '
        + 'iPad, in Safari, and writes one file containing every plate.'],
      ['How big is the Bambu P1S bed?',
        'About 256 x 256 x 250 mm. The A1 mini is 180 mm in each direction, and '
        + 'the H2D is roughly 350 x 320 x 325 mm.'],
      ['Can I split a model into parts on an iPad?',
        'Yes. It runs in the browser, so nothing is installed and the model is '
        + 'not uploaded anywhere.'],
    ],
  },

  {
    slug: 'print-an-ai-generated-model',
    title: 'How to print an AI-generated 3D model from an iPad',
    description:
      'Take a model produced by a text-to-3D tool and get it printed on a Bambu '
      + 'Lab printer using only an iPad -- including the three things generated '
      + 'models always get wrong.',
    h1: 'Printing an AI-generated model',
    lede:
      'Text-to-3D tools will hand you an STL or OBJ in a minute. Getting that '
      + 'onto a printer is the other half, and from an iPad it used to have no '
      + 'answer at all. <a href="/">' + BRAND + '</a> takes the file the '
      + 'generator gave you, sizes it, stands it up, gives it a flat bottom if '
      + 'it needs one, and writes a print-ready Bambu file -- in Safari, on the '
      + 'iPad.',
    sections: [
      ['The three things generated models get wrong', [
        '<h3>They have no size</h3>'
        + '<p>A generated model is usually a couple of units tall, or a couple '
        + 'of thousand, with no relationship to millimetres at all. Whatever it '
        + 'arrives as, type the height you actually want.</p>'
        + '<h3>They are rarely the right way up</h3>'
        + '<p>Generators do not think about which face touches the plate. Each '
        + 'piece is stood up in a way that will print, and you can turn it '
        + 'yourself if you disagree.</p>'
        + '<h3>They have no flat face</h3>'
        + '<p>This is the big one. A generated figure is a closed shape '
        + 'floating in space, touching the plate at a single point. Taking a '
        + 'slice off the bottom gives it something to stand on, and you choose '
        + 'how deep the cut goes while watching the footprint it produces.</p>',
      ]],
      ['Getting the file out of the generator and into Files', [
        '<p>Download it in Safari and it lands in Files, under Downloads. If '
        + 'the tool only offers GLB or GLTF, look for an STL or OBJ option -- '
        + 'those are what a printer wants, and most generators offer at least '
        + 'one of them.</p>',
      ]],
      ['What it will not fix', [
        '<p>Generated models are frequently hollow where they should be solid, '
        + 'or carry detail finer than a nozzle can lay down, or are made of '
        + 'surfaces that do not quite close up into a solid object. Sizing and '
        + 'standing up will not repair any of that. If a print fails in a way '
        + 'that looks like the model rather than the printer, the honest answer '
        + 'is usually to generate it again from a simpler prompt.</p>',
      ]],
    ],
    faq: [
      ['Can I 3D print an AI-generated model from an iPad?',
        'Yes. Download the STL or OBJ the generator produced, open Handoff3D in '
        + 'Safari, size it, flatten the bottom if it needs one, and save a '
        + 'print-ready Bambu file. Bambu Handy then sends it to the printer.'],
      ['Why will my AI-generated model not sit flat on the plate?',
        'Text-to-3D tools produce closed shapes floating in space, with no flat '
        + 'face anywhere on them. Cutting a thin slice off the bottom gives the '
        + 'model a flat footprint to stand on.'],
      ['What file should I export from an AI 3D generator?',
        'STL or OBJ. Both are read directly. GLB and GLTF are display formats, '
        + 'and most printing tools, this one included, do not take them.'],
    ],
  },

  {
    slug: 'how-to-print-from-an-ipad',
    title: 'Getting a file from your iPad to a Bambu printer',
    description:
      'The exact taps that move a prepared file from the Files app to a Bambu '
      + 'Lab printer, through MakerWorld and Bambu Handy, with no computer '
      + 'involved.',
    h1: 'Getting the file to the printer',
    lede:
      'Once you have a print-ready file on your iPad, this is how it reaches '
      + 'the machine. <b>It is clunky, and it is not you.</b> Bambu does not '
      + 'let other apps talk to your printer directly, so the file has to go up '
      + 'to your own private page first. It is a handful of taps, once per '
      + 'model, and no computer is involved.',
    sections: [
      ['The six steps', [
        '<ol>'
        + '<li><b>Get the file into Files.</b> iCloud Drive or On My iPad, '
        + 'either works. If it arrived by AirDrop or e-mail, tap Share and '
        + 'choose Save to Files.</li>'
        + '<li><b>Open makerworld.com in Safari</b> and sign in. You only have '
        + 'to sign in once -- it remembers you after that.</li>'
        + '<li><b>Tap Upload, then Choose file</b>, and pick the file you just '
        + 'saved.</li>'
        + '<li><b>Add a picture.</b> MakerWorld asks for a photo here and will '
        + 'not take a rendered one. Any real photo from your camera roll gets '
        + 'you through, and the model is private, so nobody else sees it.</li>'
        + '<li><b>Set it to Private, then Publish.</b> Any title at all will '
        + 'do. Private is the part that matters -- it keeps the model '
        + 'yours.</li>'
        + '<li><b>Open Bambu Handy and print it.</b> Tap your profile picture, '
        + 'top left, then 3D Models. Yours is at the top of the list. Pick your '
        + 'printer and your colour, and print.</li>'
        + '</ol>',
      ]],
      ['If you cannot find it in Handy', [
        '<p>There is a second route to the same place. Open the <b>Me</b> tab. '
        + 'There is a row of things like printing history and print queue -- '
        + '<b>slide that row to the right</b> until you see <b>My '
        + 'Creations</b>, and your model is in there.</p>',
      ]],
      ['Keep it private until you have printed it', [
        '<div class="card"><p>MakerWorld only lets a model be made public once '
        + 'you have printed it yourself and can show a photo of the real thing. '
        + 'Making one public without that photo breaks the terms you agreed to '
        + 'when you signed up. Leave it private -- nothing about printing it '
        + 'needs it to be public.</p></div>',
      ]],
      ['You are the one at the printer', [
        '<div class="card"><p>Nobody has printed your file before you. Whether '
        + 'the settings suit your machine is yours to check: stay with it for '
        + 'the first few minutes and stop the printer if anything does not look '
        + 'right. Any damage to your printer, or to anything else, is your '
        + 'responsibility and not this tool&#x27;s.</p></div>',
      ]],
    ],
    faq: [
      ['How do I send a file to a Bambu printer from an iPad?',
        'Upload it to MakerWorld as a private model in Safari, then open Bambu '
        + 'Handy, find it under your profile in 3D Models, and print it. There '
        + 'is no way for a third-party app to hand a file to the printer '
        + 'directly.'],
      ['Why do I have to upload to MakerWorld to print my own file?',
        'Bambu printers accept work from Bambu software and the Bambu cloud, '
        + 'and MakerWorld is the only route into that cloud from an iPad. '
        + 'Setting the model to Private means nobody else can see it.'],
      ['Can I keep the model private on MakerWorld and still print it?',
        'Yes. A private model prints exactly the same way. MakerWorld requires '
        + 'a photo of a real print before it will let you make one public at '
        + 'all.'],
    ],
  },

  {
    slug: 'bambu-studio-alternative-ipad',
    title: 'A Bambu Studio alternative for iPad, and where it stops',
    description:
      'Handoff3D is a free browser-based Bambu print preparation tool for iPad. '
      + 'What it does, what Bambu Studio still does better, and an honest '
      + 'comparison of both.',
    h1: 'A Bambu Studio alternative for iPad',
    lede:
      '<b>' + BRAND + ' is a free, browser-based Bambu print preparation tool '
      + 'for iPad.</b> Bring an STL, 3MF, OBJ or PLY file, choose your Bambu '
      + 'printer and nozzle, resize or turn the model, split it across plates '
      + 'if it is too big for the bed, and save a Bambu-compatible project '
      + 'file -- without a Windows or Mac computer anywhere in the loop. It is '
      + 'not a full replacement for Bambu Studio, and the rest of this page is '
      + 'about exactly where the line falls.',
    sections: [
      ['What each one is for', [
        '<p><b>Bambu Studio</b> is the real thing: a desktop slicer that turns '
        + 'a model into the instructions a printer follows, with control over '
        + 'every part of how it does it. It runs on Windows, macOS and Linux, '
        + 'and there is <a href="/bambu-studio-on-ipad">no iPad version</a>.</p>',
        '<p><b>' + BRAND + '</b> does the preparation half in a browser: size, '
        + 'orientation, plate layout, and writing a project file the Bambu '
        + 'ecosystem accepts. The printer does the slicing when you send it. '
        + 'That covers the common case -- somebody else&#x27;s model, a '
        + 'sensible size, standard settings -- which is most prints, and it '
        + 'was the case with no iPad answer at all.</p>',
      ]],
      ['Side by side, honestly', [
        '<div class="scroll"><table>'
        + '<tr><th></th><th>' + BRAND + '</th><th>Bambu Studio</th></tr>'
        + '<tr><td>Runs on an iPad</td><td>Yes</td><td>No</td></tr>'
        + '<tr><td>Needs Windows or a Mac</td><td>No</td><td>Yes</td></tr>'
        + '<tr><td>Costs anything</td><td>No</td><td>No</td></tr>'
        + '<tr><td>Reads STL, 3MF, OBJ, PLY</td><td>Yes</td><td>Yes</td></tr>'
        + '<tr><td>Resize and re-orient</td><td>Yes</td><td>Yes</td></tr>'
        + '<tr><td>Flatten a curved bottom</td><td>Yes</td><td>Yes</td></tr>'
        + '<tr><td>Split across plates</td><td>Yes</td><td>Yes</td></tr>'
        + '<tr><td>Writes a Bambu project file</td><td>Yes</td><td>Yes</td></tr>'
        + '<tr><td>Supports painted on by hand</td><td>No</td><td>Yes</td></tr>'
        + '<tr><td>Per-object and painted settings</td><td>No</td><td>Yes</td></tr>'
        + '<tr><td>Multi-colour and AMS assignment</td><td>No</td><td>Yes</td></tr>'
        + '<tr><td>Custom filament profiles</td><td>No</td><td>Yes</td></tr>'
        + '<tr><td>Preview of what the printer will do</td><td>No</td><td>Yes</td></tr>'
        + '<tr><td>A full slicer</td><td>No</td><td>Yes</td></tr>'
        + '</table></div>',
        '<p>If you have a computer, use Bambu Studio. It is free, and it is '
        + 'better at its job than any web page. This is for the case where '
        + 'there is no computer to use it on.</p>',
      ]],
      ['The other ways to do this', [
        '<p><b>Bambu Handy</b> is Bambu&#x27;s own iOS app, and you will need '
        + 'it either way -- it is what actually sends a file to the machine. '
        + 'What it does not do is take a model you downloaded and turn it into '
        + 'something printable at the size you want. It prints what is already '
        + 'a print.</p>',
        '<p><b>A desktop you can reach remotely.</b> If there is a PC at home, '
        + 'a remote desktop app on the iPad gets you the whole of Bambu Studio, '
        + 'and that is strictly more capable than anything here. It is not an '
        + 'answer if the iPad is the only computer.</p>',
        '<p><b>Cloud slicing services.</b> Several exist that will slice for '
        + 'Bambu machines in a browser, and one may suit you better than this '
        + 'does -- most want an account, and what they support changes often '
        + 'enough that it is worth checking rather than taking anybody&#x27;s '
        + 'word for it, including this page&#x27;s.</p>',
      ]],
      ['What it deliberately does not try to do', [
        '<p>It writes the standard settings for the machine and nozzle you '
        + 'chose, correctly, and nothing beyond that. No supports placed by '
        + 'hand, no painted-on settings, no tuning. Every object in the file is '
        + 'assigned to one extruder, so <b>multi-colour and AMS colour '
        + 'assignment are not supported</b> -- an AMS will happily print the '
        + 'result, in whichever single filament you pick when you send it.</p>',
        '<p>Saying so is the point. A tool that claimed to replace a slicer and '
        + 'then quietly did less would waste a print, and the failure would '
        + 'happen at the machine rather than on the screen.</p>',
      ]],
    ],
    faq: [
      ['What is the best Bambu Studio alternative for iPad?',
        'There is no full slicer for iPad, so the honest answer depends on what '
        + 'you need. Handoff3D prepares a Bambu-compatible project file in the '
        + 'browser -- sizing, orientation, plate splitting -- and Bambu Handy '
        + 'sends it to the printer. For full slicing control you need Bambu '
        + 'Studio on a desktop, or remote access to one.'],
      ['Is Handoff3D a slicer?',
        'No. It prepares a Bambu project file: the model at the size and '
        + 'orientation you chose, with the standard settings for your machine '
        + 'and nozzle. The slicing happens when the file is sent to print.'],
      ['Does Handoff3D replace Bambu Studio?',
        'Not for everything. It covers preparing a model on an iPad, which is '
        + 'the case Bambu Studio cannot cover at all. It does not do painted '
        + 'settings, hand-placed supports, custom filament profiles or '
        + 'multi-colour assignment.'],
      ['Does it work with the AMS?',
        'An AMS will print the file, in whichever single filament you select '
        + 'when you send it. What is not supported is assigning different '
        + 'colours or materials to different parts -- every object in the file '
        + 'is assigned to one extruder.'],
      ['Do I need an account, and is my model uploaded?',
        'No account, and the model is not uploaded. It is read, measured and '
        + 'rewritten inside the browser tab on your own device.'],
    ],
  },

  {
    slug: 'bambu-project-3mf',
    title: 'A Bambu project 3MF is not the same thing as a 3MF',
    description:
      'Why a plain 3MF opens on a Bambu printer with none of its settings, what '
      + 'a Bambu project file carries that a generic one does not, and how to '
      + 'get one without a desktop slicer.',
    h1: 'What makes a Bambu project file different',
    lede:
      'Both end in <b>.3mf</b> and only one of them will print the way you '
      + 'meant. A generic 3MF is a shape. A Bambu project file is a shape plus '
      + 'every decision about how to print it -- which machine, which nozzle, '
      + 'layer height, supports, what sits on which plate -- and Bambu Studio '
      + 'is strict about which one it thinks it has been handed.',
    sections: [
      ['The one string that decides it', [
        '<p>Bambu Studio reads print settings only from a file whose '
        + '<code>Application</code> metadata declares Bambu Studio format. '
        + 'Anything else is treated as a foreign import: the geometry comes in '
        + 'and <b>every setting is discarded</b>, with the message <i>"The 3mf '
        + 'file has invalid config, load geometry data only"</i>.</p>',
        '<div class="card"><p>This was measured, not guessed. A genuine Bambu '
        + 'config copied verbatim into a container of ours was <i>also</i> '
        + 'rejected, which ruled out the settings themselves. Swapping the '
        + 'container apart one member at a time narrowed it to a single line '
        + 'inside the model file -- the name of the application that wrote '
        + 'it.</p></div>',
        '<p>So a file exported as "3MF" by a modelling app, a scanner, or a '
        + 'text-to-3D tool cannot carry print settings to a Bambu machine, no '
        + 'matter what is in it. There is nowhere in a generic 3MF for them to '
        + 'live that Bambu Studio will read.</p>',
      ]],
      ['What the project file carries that a plain one does not', [
        '<p>Roughly five hundred settings, resolved against the profile tree '
        + 'for the exact machine and nozzle, plus the parts a generic 3MF has '
        + 'no concept of:</p>',
        '<ul>'
        + '<li>Which plate each object belongs to, and where on it</li>'
        + '<li>Rendered previews of each plate -- what MakerWorld shows as the '
        + 'listing image</li>'
        + '<li>Per-object settings, and the relationships that tie the '
        + 'thumbnails to the container</li>'
        + '<li>The 3MF <b>production extension</b>, which is how each part gets '
        + 'its own geometry file and a stable identity</li>'
        + '</ul>',
        '<p>None of that is exotic, but all of it has to be right at once. Two '
        + 'mistakes in particular produce a file that <i>opens perfectly</i> '
        + 'and is still wrong: parts assigned to plates by a label rather than '
        + 'by where they sit in space, which silently drops them, and a build '
        + 'transform written the wrong way round, which prints the object '
        + 'mirrored while every measurement of it stays correct.</p>',
      ]],
      ['Getting one on an iPad', [
        '<p>Producing this file is the entire job of <a href="/">' + BRAND
        + '</a>, and it does it in Safari without a desktop slicer anywhere in '
        + 'the loop. You bring an STL, 3MF, OBJ or PLY; you pick the machine '
        + 'and the nozzle; it writes the project file, and MakerWorld and Bambu '
        + 'Studio both accept it.</p>',
        '<p>What it does not do is decide how the print should go -- there is '
        + 'no support painting and no custom profile. It writes the standard '
        + 'settings for the machine you chose, correctly, which is the thing '
        + 'that was impossible without a computer.</p>',
      ]],
      ['Why a plain 3MF or STL still prints something', [
        '<p>Because the geometry is fine. Hand a printer a shape with no '
        + 'settings and the software falls back to its defaults, so you get an '
        + 'object -- at whatever size the file happened to be saved at, on '
        + 'whichever face it happened to be resting, with whatever profile was '
        + 'last selected. It prints. It is just not what you chose.</p>',
      ]],
    ],
    faq: [
      ['What is the difference between a 3MF and a Bambu project file?',
        'A generic 3MF carries geometry. A Bambu project file carries geometry '
        + 'plus the full print configuration -- machine, nozzle, layer height, '
        + 'supports, plate layout and plate previews. Bambu Studio reads those '
        + 'settings only from a file whose Application metadata declares Bambu '
        + 'Studio format; from any other 3MF it loads the geometry and discards '
        + 'every setting.'],
      ['Why does Bambu Studio say "invalid config, load geometry data only"?',
        'Because the file does not declare itself as a Bambu Studio file. The '
        + 'settings inside can be perfectly valid and are still discarded -- it '
        + 'is the Application metadata that decides, not the settings.'],
      ['Can I make a Bambu project 3MF without Bambu Studio?',
        'Yes. Handoff3D writes one in the browser, on an iPad, and both '
        + 'MakerWorld and Bambu Studio accept the result.'],
      ['Will a plain STL print on a Bambu printer?',
        'The shape will. It arrives with no size you chose, no orientation you '
        + 'chose and no settings, so the printer uses defaults for all three.'],
    ],
  },

  {
    slug: 'makerworld-on-ipad',
    title: 'Using MakerWorld on an iPad, start to finish',
    description:
      'Download a model from MakerWorld on an iPad, prepare it without a '
      + 'computer, upload it back as a private model, and print it through '
      + 'Bambu Handy.',
    h1: 'MakerWorld on an iPad',
    lede:
      'MakerWorld works fine in Safari on an iPad -- browsing it, downloading '
      + 'from it and uploading to it all work. The gap has always been the '
      + 'middle: turning what you downloaded into something your printer will '
      + 'take. That step now runs in the browser too, so the whole round trip '
      + 'is possible on the iPad alone.',
    sections: [
      ['The round trip', [
        '<ol>'
        + '<li><b>Download the model.</b> On a MakerWorld listing, take the '
        + 'model file rather than a print profile. In Safari it lands in Files, '
        + 'under Downloads.</li>'
        + '<li><b>Prepare it.</b> Open <a href="/">' + BRAND + '</a>, choose '
        + 'the file, pick your printer, set the size. If it is too big for the '
        + 'bed you can split it across plates here.</li>'
        + '<li><b>Upload it back, privately.</b> Tap Upload on MakerWorld, '
        + 'choose the file you just made, add any photo from your camera roll, '
        + 'set visibility to <b>Private</b>, and publish.</li>'
        + '<li><b>Print from Bambu Handy.</b> Profile picture, then 3D Models. '
        + 'Yours is at the top.</li>'
        + '</ol>',
        '<p>The full detail of the last two steps, including the second route '
        + 'to your own models inside Handy, is on <a href="/how-to-print-from-'
        + 'an-ipad">getting the file to the printer</a>.</p>',
      ]],
      ['Why you upload to MakerWorld to print your own file', [
        '<p>It looks absurd the first time: the model came from MakerWorld, and '
        + 'now it goes back. The reason is that <b>no third-party app can hand '
        + 'a file to a Bambu printer</b>. The machine takes work from '
        + 'Bambu&#x27;s own software and Bambu&#x27;s own cloud, and from an '
        + 'iPad the only door into that cloud is MakerWorld.</p>',
        '<p>Set the model to Private and it is yours alone -- it does not '
        + 'appear in search, on your profile, or anywhere else. Printing works '
        + 'exactly the same.</p>',
      ]],
      ['When a print profile is not enough', [
        '<p>Many MakerWorld listings include ready-made print profiles, and '
        + 'when one exists for your exact machine you should use it -- it will '
        + 'be better tuned than anything generated automatically.</p>',
        '<p>It stops being enough the moment you want something different from '
        + 'what the designer published: a different size, a different printer '
        + 'from the one they used, one piece out of a set, or a model that '
        + 'never had a profile in the first place. That is the case this fills, '
        + 'and it is most downloads.</p>',
      ]],
      ['Keep it private until it has been printed', [
        '<div class="card"><p>MakerWorld only allows a model to be made public '
        + 'once you have printed it and can show a photo of the real thing. '
        + 'Publishing without that photo breaks the terms you agreed to when '
        + 'you signed up -- and a rendered picture will not do, which is why '
        + 'the upload asks for a camera roll photo.</p></div>',
      ]],
    ],
    faq: [
      ['Can I use MakerWorld on an iPad?',
        'Yes. Browsing, downloading and uploading all work in Safari. The step '
        + 'that used to need a desktop was preparing the model in between, and '
        + 'Handoff3D does that in the browser.'],
      ['How do I upload my own model to MakerWorld from an iPad?',
        'Tap Upload, then Choose file, and pick the file from your Files app. '
        + 'MakerWorld requires a photo, which any picture from your camera roll '
        + 'satisfies, and you can set the model to Private so nobody else sees '
        + 'it.'],
      ['Do I have to make my model public on MakerWorld to print it?',
        'No. A private model prints identically. MakerWorld requires a photo of '
        + 'a real print before it will let you make one public at all.'],
      ['Why can I not send a file straight from my iPad to my Bambu printer?',
        'There is no public way for a third-party app to hand a file to a Bambu '
        + 'printer. It accepts work from Bambu software and the Bambu cloud, '
        + 'and MakerWorld is the route into that cloud from an iPad.'],
    ],
  },

  {
    slug: 'bambu-printers-on-ipad',
    title: 'Every Bambu printer, and what fits on it, from an iPad',
    description:
      'Build volumes, nozzle sizes and materials for the A1 mini, A1, P1P, '
      + 'P1S, P2S, X1, X1 Carbon, X1E, X2D, A2L, H2C, H2S, H2D and H2D Pro -- '
      + 'and how to prepare a file for any of them on an iPad.',
    h1: 'Which Bambu printer, and what fits on it',
    lede:
      'All fourteen current Bambu Lab machines are supported, with bed sizes '
      + 'and print settings taken from Bambu Studio&#x27;s own profiles rather '
      + 'than guessed at. Pick yours in <a href="/">' + BRAND + '</a> and the '
      + 'plate drawn under your model is the real one, at the real size.',
    sections: [
      ['Build volumes', [
        '<div class="scroll"><table>'
        + '<tr><th>Printer</th><th>Build volume</th></tr>'
        + '<tr><td>A1 mini</td><td>180 &times; 180 &times; 180 mm</td></tr>'
        + '<tr><td>A1</td><td>256 &times; 256 &times; 256 mm</td></tr>'
        + '<tr><td>P1P, P1S</td><td>256 &times; 256 &times; 250 mm</td></tr>'
        + '<tr><td>P2S</td><td>256 &times; 256 &times; 256 mm</td></tr>'
        + '<tr><td>X1, X1 Carbon, X1E</td><td>256 &times; 256 &times; 250 mm</td></tr>'
        + '<tr><td>X2D</td><td>256 &times; 256 &times; 261 mm</td></tr>'
        + '<tr><td>A2L, H2C</td><td>330 &times; 320 &times; 325 mm</td></tr>'
        + '<tr><td>H2S</td><td>340 &times; 320 &times; 340 mm</td></tr>'
        + '<tr><td>H2D, H2D Pro</td><td>350 &times; 320 &times; 325 mm</td></tr>'
        + '</table></div>',
        '<p>Anything larger than the box for your machine has to be scaled '
        + 'down, stood differently, or cut up -- see <a href="/split-a-model-'
        + 'too-big-for-your-bed">when a model is too big for the bed</a>.</p>',
      ]],
      ['The nozzle is a printer, not a setting', [
        '<p>This surprises people, and it matters more than it sounds. On a '
        + 'Bambu machine there is no "0.6 mm option" you apply to a P1S. '
        + '<b>"P1S with a 0.6 nozzle" is its own machine profile</b>, with its '
        + 'own layer heights and its own line widths throughout. Choosing the '
        + 'printer and choosing the nozzle is really one decision.</p>',
        '<p>Which is why the nozzle is not remembered between visits: your '
        + 'machine is, but the nozzle starts at 0.4 every time. A nozzle gets '
        + 'swapped for one print and swapped back, and a file built for 0.8 mm '
        + 'on a printer still wearing a 0.4 is a machine pushing four times the '
        + 'plastic through a quarter of the hole.</p>',
        '<p>Two consequences worth knowing:</p>'
        + '<ul>'
        + '<li><b>Only the 0.4 nozzle has a "0.20mm Standard" profile.</b> A '
        + '0.2 mm nozzle cannot lay a 0.2 mm layer, so each nozzle has its own '
        + 'standard: 0.10 mm for the 0.2 nozzle, 0.30 for the 0.6, 0.40 for the '
        + '0.8.</li>'
        + '<li><b>No 0.2 mm nozzle can print TPU</b> on any machine.</li>'
        + '</ul>',
      ]],
      ['Materials, by machine', [
        '<p>The material list offered is the one the machine actually has '
        + 'profiles for, not a generic list. Two families differ from the '
        + 'rest:</p>',
        '<ul>'
        + '<li><b>A1 mini and A2L have no ABS at all.</b> They are open-frame, '
        + 'and Bambu publishes no ABS profile for them.</li>'
        + '<li><b>Every other machine offers PLA, PETG and ABS</b>, with TPU on '
        + 'every nozzle except the 0.2.</li>'
        + '</ul>',
        '<p>This is not a detail you can safely paper over: asking for ABS on a '
        + 'machine that has no ABS profile used to hand back a PETG one instead '
        + '-- a file saying ABS on it, built entirely from PETG settings.</p>',
      ]],
      ['Preparing a file for any of them', [
        '<p>Same on every machine: open <a href="/">' + BRAND + '</a> in '
        + 'Safari, choose your model, pick the printer and nozzle, set the '
        + 'size, save. There is no version of Bambu Studio for iPad -- see '
        + '<a href="/bambu-studio-on-ipad">what works and what does not</a> -- '
        + 'and this covers the common case without one.</p>',
      ]],
    ],
    faq: [
      ['What is the build volume of the Bambu P1S?',
        '256 x 256 x 250 mm. The A1 is 256 x 256 x 256 mm, the A1 mini is 180 x '
        + '180 x 180 mm, and the H2D is 350 x 320 x 325 mm.'],
      ['Which Bambu printers work with Handoff3D?',
        'All fourteen current models: A1 mini, A1, P1P, P1S, P2S, X1, X1 '
        + 'Carbon, X1E, X2D, A2L, H2C, H2S, H2D and H2D Pro, each in 0.2, 0.4, '
        + '0.6 and 0.8 mm nozzle versions.'],
      ['Is the nozzle size a setting I choose separately?',
        'No. On a Bambu machine each nozzle is a distinct machine profile with '
        + 'its own layer heights and line widths, so the printer and the nozzle '
        + 'are one choice, not two.'],
      ['Can the A1 mini print ABS?',
        'No. The A1 mini and the A2L are open-frame and Bambu publishes no ABS '
        + 'profile for either. Every other current model offers PLA, PETG and '
        + 'ABS.'],
      ['Can a 0.2 mm nozzle print TPU?',
        'No, on any Bambu machine. It also cannot lay a 0.2 mm layer -- its '
        + 'standard profile is 0.10 mm.'],
    ],
  },
  {
    slug: 'simplyprint-on-ipad',
    title: 'SimplyPrint on an iPad: the computer it still needs',
    description:
      'SimplyPrint slices in a browser on an iPad, but sending the result to a '
      + 'Bambu printer needs the SimplyPrint client running on an always-on PC, '
      + 'Mac, Linux box or Raspberry Pi. What each half needs, and what an iPad '
      + 'can do on its own.',
    h1: 'SimplyPrint on an iPad, and the hardware behind it',
    lede:
      'Ask anything -- a search box, or an AI -- how to print from an iPad and '
      + 'SimplyPrint is usually the first answer back. Half of that answer is '
      + 'right: <b>its cloud slicer really does run in Safari on an iPad</b>, on '
      + 'real slicing engines, and it is good. The half that does not is getting '
      + 'the result to a Bambu printer. That goes through the SimplyPrint '
      + 'client, and the client needs a computer that stays switched on -- '
      + 'SimplyPrint&#x27;s own documentation says a phone or a tablet cannot '
      + 'run it.',
    sections: [
      ['Which half works on an iPad alone', [
        '<div class="scroll"><table class="compare">'
        + '<tr><th>Step</th><th>SimplyPrint</th><th>' + BRAND + '</th></tr>'
        + '<tr><td>Open a model on the iPad</td><td>Yes</td><td>Yes</td></tr>'
        + '<tr><td>Resize it to a measurement</td><td>Yes</td><td>Yes</td></tr>'
        + '<tr><td>Prepare it for a Bambu machine</td><td>Yes, on their '
        + 'servers</td><td>Yes, on the iPad</td></tr>'
        + '<tr><td>Save a file you can use</td><td>Yes</td><td>Yes</td></tr>'
        + '<tr><td>Send it to the printer</td><td>Needs a second computer'
        + '</td><td>Goes through Bambu Handy</td></tr>'
        + '<tr><td>Watch the print remotely</td><td>Needs a second computer'
        + '</td><td>Bambu Handy, as usual</td></tr>'
        + '</table></div>',
        '<p>So the honest version of "no computer needed" is: no computer to '
        + '<i>prepare</i> a file, on either. A computer to <i>send</i> one, on '
        + 'SimplyPrint.</p>',
      ]],
      ['Why the client needs its own machine', [
        '<p>SimplyPrint is a cloud service, and its cloud cannot talk to a '
        + 'Bambu printer by itself. The link runs through a small program -- the '
        + 'SimplyPrint client -- sitting on your network, holding a connection '
        + 'open to the printer at one end and to SimplyPrint at the other. It '
        + 'has to be awake whenever you want to start a print, so it wants a '
        + 'machine that is always on.</p>',
        '<div class="card"><p>That machine can be a Windows PC, a Mac, a Linux '
        + 'box or a Raspberry Pi. It cannot be an iPad or a phone: iPadOS and '
        + 'iOS will not let an app hold a background connection open like that, '
        + 'and SimplyPrint says so plainly rather than pretending otherwise. A '
        + 'Raspberry Pi is the usual answer, and it is the cheapest one, but it '
        + 'is still a computer to buy, set up and leave running.</p></div>',
        '<p>The printer having Wi-Fi does not change this. An A1 mini is on your '
        + 'network already; what is missing is something the cloud service is '
        + 'allowed to speak to it through.</p>',
      ]],
      ['What this page is offering instead', [
        '<p><b>' + BRAND + ' never sends anything to your printer</b>, which is '
        + 'exactly why it needs no bridge and no second machine. It prepares the '
        + 'file and stops there, and the file travels the rest of the way on '
        + 'Bambu&#x27;s own rails: save it to Files, upload it to MakerWorld as '
        + 'a private model, open Bambu Handy, print. That path already works '
        + 'from an iPad and needs nothing new switched on.</p>',
        '<p>It runs in Safari, costs nothing, has no account, and the model does '
        + 'not leave the iPad -- it is read, measured and rewritten in the '
        + 'browser tab. Out comes a Bambu project 3MF for the machine and nozzle '
        + 'you picked. Full walk-through: <a href="/how-to-print-from-an-ipad">'
        + 'getting the file to the printer</a>.</p>',
      ]],
      ['Where SimplyPrint is the better answer', [
        '<p>This is not a page saying do not use it. If you have a computer that '
        + 'is on anyway, or you are willing to add a Raspberry Pi, SimplyPrint '
        + 'does a great deal that this does not do at all:</p>',
        '<ul>'
        + '<li><b>Starting prints remotely</b>, and a print queue across several '
        + 'machines</li>'
        + '<li><b>Monitoring</b> -- camera, progress, failure alerts, in one '
        + 'place for a whole farm</li>'
        + '<li><b>Real slicer settings</b>: it runs actual Bambu Studio, '
        + 'OrcaSlicer and PrusaSlicer engines on its servers, so custom '
        + 'profiles, supports and all the rest are there</li>'
        + '<li><b>Your files in one library</b>, on any device</li>'
        + '</ul>',
        '<p>' + BRAND + ' has none of that and is not trying to. It writes the '
        + 'standard settings for the machine you chose, correctly, and that is '
        + 'the whole feature. No hand-placed supports, no custom profiles, no '
        + 'multi-colour assignment, no monitoring.</p>',
        '<p>The two also sit at different prices. SimplyPrint has a free tier '
        + 'for a couple of printers and paid plans above it; the bridge computer '
        + 'is on top of whichever plan you are on. This is free, with nothing to '
        + 'sign up for.</p>',
      ]],
      ['The other difference: where your model goes', [
        '<p>Cloud slicing means the model is uploaded. It has to be -- the '
        + 'engine is running on a server, so the file goes to the server. That '
        + 'is a normal, reasonable trade for what you get back, and it is worth '
        + 'knowing you are making it.</p>',
        '<p>' + BRAND + ' has no server to upload to. Everything -- reading the '
        + 'file, measuring it, standing it up, cutting it, drawing the plate '
        + 'picture, writing the finished project file -- happens in the browser '
        + 'on your device. The one thing that does leave is anonymous counting '
        + 'of how many people opened the page and how far they got. Your model, '
        + 'its name and every measurement taken from it stay put.</p>',
      ]],
      ['If you already tried SimplyPrint and stopped at the client', [
        '<p>That is the common way to land here, and nothing was done wrong -- '
        + 'the slicing part worked, and then setup asked for a machine you do '
        + 'not have. You do not need to undo any of it. Open <a href="/">'
        + BRAND + '</a>, prepare the file on the iPad, and send it with Handy '
        + 'the way you already send everything else.</p>',
        '<p>Related: <a href="/bambu-studio-on-ipad">Bambu Studio on iPad</a>, '
        + 'and <a href="/bambu-studio-alternative-ipad">what an alternative can '
        + 'and cannot be</a>.</p>',
      ]],
    ],
    faq: [
      ['Can I use SimplyPrint with a Bambu printer without a computer?',
        'Not for sending prints. SimplyPrint connects to a Bambu printer '
        + 'through the SimplyPrint client, which has to run on a Windows PC, a '
        + 'Mac, a Linux machine or a Raspberry Pi that stays switched on. You '
        + 'can use its cloud slicer from an iPad without any of that, but the '
        + 'result has to reach the printer some other way.'],
      ['Can the SimplyPrint client run on an iPad or an iPhone?',
        'No. SimplyPrint states that mobile devices cannot run the background '
        + 'process the client needs. An iPad can control and watch printers '
        + 'through SimplyPrint once a bridge machine is running somewhere else.'],
      ['My A1 mini has Wi-Fi. Why is another device needed at all?',
        'The printer is on your network, but SimplyPrint runs in the cloud and '
        + 'reaches it through a local client rather than directly. The bridge '
        + 'is the thing that holds a connection to both ends.'],
      ['Do I have to buy a Raspberry Pi?',
        'Only if you have no other computer that is left on. Any Windows, Mac '
        + 'or Linux machine that is awake when you want to print will do; a '
        + 'Raspberry Pi is just the cheapest one to leave running.'],
      ['Is there a way to prepare a Bambu file on an iPad with no extra '
       + 'hardware at all?',
        'Yes. Handoff3D runs in Safari on the iPad, resizes and arranges the '
        + 'model and writes a Bambu project 3MF on the device. Save it to '
        + 'Files, upload it to MakerWorld as a private model and print it from '
        + 'Bambu Handy. Nothing else is installed and nothing else has to be '
        + 'switched on.'],
      ['Is SimplyPrint free?',
        'There is a free tier covering a small number of printers, with paid '
        + 'plans above it. The bridge computer is a separate cost either way.'],
    ],
  },
]

/** Short label for a page, used in the footer links between them. */
export const LABEL = {
  'bambu-studio-on-ipad': 'Bambu Studio on iPad',
  'resize-a-model-on-ipad': 'Resizing a model on an iPad',
  '3d-print-from-ipad': '3D printing from an iPad, with no computer',
  'split-a-model-too-big-for-your-bed': 'When a model is too big for the bed',
  'print-an-ai-generated-model': 'Printing an AI-generated model',
  'how-to-print-from-an-ipad': 'Getting the file to the printer',
  'bambu-project-3mf': 'What makes a Bambu project file different',
  'makerworld-on-ipad': 'MakerWorld on an iPad',
  'bambu-printers-on-ipad': 'Which Bambu printer, and what fits on it',
  'bambu-studio-alternative-ipad': 'A Bambu Studio alternative for iPad',
  'simplyprint-on-ipad': 'SimplyPrint on an iPad, and the hardware behind it',
}

/**
 * The one sentence every page is a variation on.
 *
 * Written down once because the point of it is that it does not vary: a
 * retrieval system learning what this is should meet the same claim, in the
 * same words, wherever it lands. Used in llms.txt below and worth reaching for
 * before inventing a new phrasing on a new page.
 */
export const ONE_LINE =
  BRAND + ' is a free, browser-based Bambu print preparation tool that creates '
  + 'Bambu-compatible project 3MF files from an iPad, without a Windows or Mac '
  + 'computer.'

/**
 * JSON-LD, two blocks per page. The FAQ is the one that earns its place -- it
 * is the shape an answer engine reads a question-and-answer off. The breadcrumb
 * is there so the page is understood as sitting under the app rather than
 * floating on its own.
 */
function jsonLd(page) {
  const faq = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: page.faq.map(([q, a]) => ({
      '@type': 'Question',
      name: q,
      acceptedAnswer: { '@type': 'Answer', text: a },
    })),
  }
  const crumbs = {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      { '@type': 'ListItem', position: 1, name: BRAND, item: SITE + '/' },
      {
        '@type': 'ListItem',
        position: 2,
        name: page.h1,
        item: SITE + '/' + page.slug,
      },
    ],
  }
  return [faq, crumbs]
    .map((o) => '<script type="application/ld+json">\n'
      + JSON.stringify(o, null, 2) + '\n</script>')
    .join('\n')
}

function faqBlock(page) {
  const items = page.faq
    .map(([q, a]) => '<h3>' + escape(q) + '</h3>\n<p>' + dashes(a) + '</p>')
    .join('\n')
  return '<h2>Common questions</h2>\n' + items
}

function footerLinks(page) {
  const others = PAGES.filter((p) => p.slug !== page.slug)
    .map((p) => '<li><a href="/' + p.slug + '">' + escape(LABEL[p.slug])
      + '</a></li>')
    .join('\n')
  return '<footer>\n<p><b>' + BRAND + '</b> is a free page that prepares 3D '
    + 'models for Bambu Lab printers on an iPad. Nothing is installed, and your '
    + 'model is not uploaded.</p>\n<ul>\n' + others + '\n</ul>\n</footer>'
}

/** One page, as a complete HTML file. */
export function renderPage(page) {
  const url = SITE + '/' + page.slug
  const body = page.sections
    .map(([heading, parts]) => '<h2>' + escape(heading) + '</h2>\n'
      + parts.map(dashes).join('\n'))
    .join('\n')

  return '<!doctype html>\n<html lang="en">\n<head>\n'
    + '<meta charset="utf-8">\n'
    + '<meta name="viewport" content="width=device-width, initial-scale=1, '
    + 'viewport-fit=cover">\n'
    + '<meta name="theme-color" content="#101215">\n'
    + '<title>' + escape(page.title) + '</title>\n'
    + '<meta name="description" content="' + escape(page.description) + '">\n'
    + '<link rel="canonical" href="' + url + '">\n'
    + '<link rel="icon" type="image/png" sizes="32x32" href="/icons/icon-32.png">\n'
    + '<meta property="og:type" content="article">\n'
    + '<meta property="og:site_name" content="' + BRAND + '">\n'
    + '<meta property="og:title" content="' + escape(page.title) + '">\n'
    + '<meta property="og:description" content="' + escape(page.description) + '">\n'
    + '<meta property="og:url" content="' + url + '">\n'
    + '<meta property="og:image" content="' + SITE + OG_IMAGE + '">\n'
    + '<meta name="twitter:card" content="summary">\n'
    + '<meta name="twitter:title" content="' + escape(page.title) + '">\n'
    + '<meta name="twitter:description" content="' + escape(page.description) + '">\n'
    + '<meta name="twitter:image" content="' + SITE + OG_IMAGE + '">\n'
    + jsonLd(page) + '\n'
    + '<style>' + CSS + '</style>\n'
    + '</head>\n<body>\n'
    + '<header><a class="home" href="/">&larr; <b>' + BRAND + '</b> &mdash; '
    + '3D print, no computer necessary</a></header>\n'
    + '<main>\n'
    + '<h1>' + escape(page.h1) + '</h1>\n'
    + '<p class="lede">' + dashes(page.lede) + '</p>\n'
    + '<a class="cta" href="/">Open ' + BRAND + '</a>\n'
    + '<p class="cta-sub">Free, no account, nothing installed. Works in Safari '
    + 'on an iPad or an iPhone.</p>\n'
    + body + '\n'
    + faqBlock(page) + '\n'
    + '<a class="cta" href="/">Open ' + BRAND + '</a>\n'
    + '</main>\n'
    + footerLinks(page) + '\n'
    + '</body>\n</html>\n'
}

/**
 * robots.txt. The default is allow, so naming the answer engines changes
 * nothing technically -- it is here because "are we blocking GPTBot" is a
 * question that gets asked, and a file that answers it in writing settles it.
 * The dashboard is behind a key and already carries its own noindex; it is
 * named here as well so it is never fetched in the first place.
 */
export function renderRobots() {
  const agents = [
    'GPTBot', 'OAI-SearchBot', 'ChatGPT-User', 'ClaudeBot', 'Claude-User',
    'anthropic-ai', 'PerplexityBot', 'Perplexity-User', 'Google-Extended',
    'Applebot-Extended', 'CCBot', 'Bingbot', 'meta-externalagent',
  ]
  return '# ' + BRAND + ' -- everything here is meant to be found.\n'
    + '# The answer engines are named explicitly so that "is this site\n'
    + '# blocking them" has a written answer rather than an assumed one.\n\n'
    + 'User-agent: *\n'
    + 'Allow: /\n'
    + 'Disallow: /dashboard\n'
    + 'Disallow: /dashboard.html\n\n'
    + agents.map((a) => 'User-agent: ' + a + '\nAllow: /\n').join('\n')
    + '\nSitemap: ' + SITE + '/sitemap.xml\n'
}

/**
 * llms.txt -- a plain-language description of the site, for a machine.
 *
 * An emerging convention rather than a standard anybody has committed to, and
 * it is included with that firmly in mind: **no retrieval system is known to
 * give this file weight**, and if one day they all ignore it, nothing here is
 * lost. It costs one generated file and it is the only artefact on the site
 * that states the whole product in one place in prose.
 *
 * Generated from PAGES rather than written out, for the reason everything else
 * here is: a hand-kept index of nine pages is a list that goes stale the first
 * time somebody adds a tenth and does not think of it.
 *
 * The limitation is in it on purpose. A description that claimed a full slicer
 * would be repeated back by whatever read it, and then somebody arrives
 * expecting painted supports and finds none. Being cited accurately is worth
 * more than being cited flatteringly.
 */
export function renderLlms() {
  const links = PAGES
    .map((p) => `- [${LABEL[p.slug]}](${SITE}/${p.slug}): ${p.description}`)
    .join('\n')
  return `# ${BRAND}\n\n> ${ONE_LINE}\n\n`
    + `${BRAND} runs entirely in the browser on the reader's own device. There\n`
    + 'is no account, nothing to install, and the model is never uploaded --\n'
    + 'it is read, measured and rewritten inside the browser tab.\n\n'
    + '## What it does\n\n'
    + '- Reads STL, 3MF, OBJ and PLY files\n'
    + '- Resizes a model to an exact measurement in millimetres\n'
    + '- Stands each part up in an orientation that will print\n'
    + '- Flattens a curved bottom so a model has a face to stand on\n'
    + '- Splits a model too large for the bed across as many plates as it needs\n'
    + '- Writes a Bambu-compatible project 3MF, accepted by MakerWorld and by\n'
    + '  Bambu Studio\n'
    + '- Supports every current Bambu Lab machine -- ' + MODELS.join(', ')
    + ' -- in 0.2, 0.4, 0.6 and 0.8 mm nozzle versions\n\n'
    + '## What it does not do\n\n'
    + `${BRAND} is not a full replacement for Bambu Studio and does not claim\n`
    + 'to be one. It has no hand-placed supports, no painted-on settings, no\n'
    + 'custom filament profiles, and no multi-colour or AMS colour assignment:\n'
    + 'every object in the file is assigned to a single extruder. It writes the\n'
    + 'standard settings for the chosen machine and nozzle, and nothing beyond\n'
    + 'that. The slicing itself happens when the file is sent to the printer.\n\n'
    + '## How a file reaches the printer\n\n'
    + 'No third-party app can hand a file to a Bambu printer directly. The file\n'
    + 'is saved to the Files app, uploaded to MakerWorld as a private model, and\n'
    + 'printed from the Bambu Handy app.\n\n'
    + `## Pages\n\n- [${BRAND}](${SITE}/): the app itself\n${links}\n`
}

/** sitemap.xml. The app first, then the pages -- all of them real files. */
export function renderSitemap(today) {
  const urls = [{ loc: SITE + '/', priority: '1.0' }].concat(
    PAGES.map((p) => ({ loc: SITE + '/' + p.slug, priority: '0.8' })))
  const body = urls
    .map(({ loc, priority }) => '  <url>\n'
      + '    <loc>' + loc + '</loc>\n'
      + '    <lastmod>' + today + '</lastmod>\n'
      + '    <changefreq>monthly</changefreq>\n'
      + '    <priority>' + priority + '</priority>\n'
      + '  </url>')
    .join('\n')
  return '<?xml version="1.0" encoding="UTF-8"?>\n'
    + '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
    + body + '\n</urlset>\n'
}
