/**
 * The pages a search engine can actually read.
 *
 * The app is a React page with an empty <div id="root"> in the HTML. Google
 * will render it eventually; the crawlers behind AI answers -- GPTBot,
 * ClaudeBot, PerplexityBot, OAI-SearchBot -- fetch the HTML and stop. To all of
 * them the product was a blank page titled "Handoff3D", which is a word nobody
 * types into a search box. These are static files with the answer written out
 * in the HTML, one page per question people actually ask.
 *
 * They are plain files in web/public/, not Vite entry points, deliberately:
 * nothing here needs bundling, and a page that must survive with JavaScript
 * switched off should not go through a JavaScript build to get there. Vercel
 * copies public/ to the site root, and `cleanUrls` in vercel.json serves them
 * without the .html. The filesystem is checked before the catch-all rewrite, so
 * they win over it without needing a rewrite of their own.
 *
 * ONE DELIBERATE BREAK WITH THE COPY RULES. Section 6 of the spec bans mesh,
 * manifold, normals, infill, gcode and slice from user-facing strings, and
 * every string in the app obeys it. These pages cannot: "slice" and "STL" are
 * the words people type, and a page that avoids them cannot be found by anyone
 * searching for them. So the jargon appears where it is the question, and the
 * answer under it is in plain words. Nothing in web/src/ is affected.
 *
 * Sources stay ASCII and typography goes in as entities, same as handoff.js.
 * Generated by build-guides.mjs; the output is committed, and
 * tests/test_guides.py fails if the two have drifted.
 */

export const SITE = 'https://bambu-print-prep.vercel.app'
export const BRAND = 'Handoff3D'

/**
 * The share picture. No render was commissioned for this -- the app icon is
 * real, square and already in the repo, and a square og:image is better than
 * the grey box a link with none at all gets.
 */
export const OG_IMAGE = '/icons/icon-512.png'

/**
 * Every Bambu machine the printer picker knows, for the pages that list them.
 * Written out rather than read from printers.json: these are static files, and
 * a generator that reached into the profile index would leave the committed
 * pages stale the moment the index changed without anything saying so.
 * tests/test_guides.py checks this list against printers.json instead, which
 * fails loudly in the direction that matters.
 */
export const MODELS = [
  'A1 mini', 'A1', 'P1P', 'P1S', 'P2S', 'X1', 'X1 Carbon', 'X1E', 'X2D',
  'A2L', 'H2C', 'H2S', 'H2D', 'H2D Pro',
]

const CSS = `
:root { color-scheme: light dark;
        --ink: #1a1a1a; --dim: #5b5b5b; --bg: #fbfaf8; --card: #fff;
        --line: #e5e2dc; --accent: #17663f; }
@media (prefers-color-scheme: dark) {
  :root { --ink: #ececec; --dim: #a6a6a6; --bg: #17181a; --card: #212327;
          --line: #34363b; --accent: #6fd39b; } }
* { box-sizing: border-box; }
body { margin: 0; padding: 0 5vw 14vw; background: var(--bg); color: var(--ink);
       font: 400 18px/1.62 -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
       -webkit-text-size-adjust: 100%; }
main, header, footer { max-width: 38rem; margin: 0 auto; }
header { padding: 1.6rem 0 .4rem; }
header a.home { color: var(--dim); text-decoration: none; font-size: .93rem; }
header a.home b { color: var(--ink); }
h1 { font-size: 1.95rem; line-height: 1.18; margin: 1.2rem 0 .6rem;
     letter-spacing: -.015em; }
h2 { font-size: 1.22rem; line-height: 1.3; margin: 2.3rem 0 .5rem; }
h3 { font-size: 1.02rem; margin: 1.5rem 0 .3rem; }
p { margin: 0 0 1rem; }
.lede { font-size: 1.12rem; margin-bottom: 1.6rem; }
ul, ol { margin: 0 0 1.1rem; padding-left: 1.3rem; }
li { margin: 0 0 .45rem; }
a { color: var(--accent); }
b { font-weight: 650; }
.cta { display: block; background: var(--accent); color: var(--bg);
       text-decoration: none; text-align: center; font-weight: 650;
       padding: .95rem 1.2rem; border-radius: 13px; margin: 2rem 0 .6rem; }
.cta-sub { text-align: center; color: var(--dim); font-size: .9rem;
           margin: 0 0 2rem; }
.card { background: var(--card); border: 1px solid var(--line);
        border-radius: 14px; padding: 1.1rem 1.25rem; margin: 0 0 1.4rem; }
.card p:last-child { margin-bottom: 0; }
footer { border-top: 1px solid var(--line); margin-top: 3rem; padding-top: 1.4rem;
         color: var(--dim); font-size: .93rem; }
footer ul { list-style: none; padding: 0; }
`

/** Python's html.escape(s, quote=True), character for character. */
export function escape(text) {
  return String(text)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#x27;')
}

/** Sources stay ASCII; the page should still read like typography. */
const dashes = (text) => text.split(' -- ').join(' &mdash; ')

/**
 * The pages. Each is a question somebody types, answered in the first
 * paragraph, because that paragraph is what an answer engine quotes.
 */
export const PAGES = [
  {
    slug: 'bambu-studio-on-ipad',
    title: 'Bambu Studio on iPad: what works, what does not',
    description:
      'Bambu Studio has no iPad version and Apple will not run one. Here is '
      + 'what you can do instead, in Safari, to get a print-ready file for a '
      + 'Bambu Lab printer without a computer.',
    h1: 'Bambu Studio on iPad',
    lede:
      '<b>There is no iPad version of Bambu Studio, and there is not going to '
      + 'be one soon.</b> Bambu Studio is a desktop program for Windows, macOS '
      + 'and Linux. It is not on the App Store, iPadOS will not run a Windows '
      + 'or macOS program, and no setting or workaround changes that. What you '
      + 'can do is prepare the file somewhere else and send it to the printer '
      + 'from your iPad -- that part works, and it works today.',
    sections: [
      ['Why it cannot simply be ported', [
        '<p>Bambu Studio is built on the same foundations as PrusaSlicer and '
        + 'OrcaSlicer: a large C++ desktop application with a desktop windowing '
        + 'toolkit under it. Getting that onto iPadOS is not a recompile, it is '
        + 'a rewrite of the entire interface, and it would still have to pass '
        + 'App Store review as a new app.</p>',
        '<p>People sometimes suggest running it in a remote desktop session '
        + 'against a PC at home. That does work, and if you already have a PC '
        + 'sitting there it is a fine answer. It is not an answer if the iPad '
        + '<i>is</i> the computer.</p>',
      ]],
      ['What an iPad can actually do', [
        '<p>Two things have to happen between a downloaded model and a printed '
        + 'object. The first is preparing it: getting it the right size, the '
        + 'right way up, and turned into a file the printer understands. The '
        + 'second is sending it to the machine.</p>',
        '<p>Sending it has always been possible from an iPad -- the Bambu Handy '
        + 'app does it. It was the first half that had no answer, and that is '
        + 'the half this page is about. <b>' + BRAND + ' does the preparing in '
        + 'Safari itself.</b> You open a web page, choose your model, pick your '
        + 'printer and your size, and it writes a finished Bambu project file '
        + 'straight into your Files app.</p>',
        '<p>It is free, there is no account, and your model is not uploaded '
        + 'anywhere -- the work happens on the iPad, inside the browser tab.</p>',
      ]],
      ['Which printers it covers', [
        '<p>Every current Bambu Lab machine, with the bed size and the print '
        + 'settings taken from Bambu Studio&#x27;s own profiles rather than '
        + 'guessed at: ' + MODELS.join(', ') + '. Each of them in 0.2, 0.4, 0.6 '
        + 'and 0.8&nbsp;mm nozzle versions, because on a Bambu machine the '
        + 'nozzle is effectively a different printer, with its own layer '
        + 'heights and its own line widths.</p>',
      ]],
      ['What you still need Bambu Studio for', [
        '<p>Plenty, and it is worth being straight about it. Supports placed by '
        + 'hand, painted-on settings, multi-colour assignment, custom filament '
        + 'profiles, tuning towers, changing anything about how the printer '
        + 'moves -- all of that is desktop work. If you have a computer, use '
        + 'Bambu Studio. It is free, and it is better at its job than any web '
        + 'page.</p>',
        '<p>What is covered here is the common case: a model somebody else '
        + 'designed, printed at a sensible size on standard settings. That is '
        + 'most prints, and it was the case with no iPad answer at all.</p>',
      ]],
    ],
    faq: [
      ['Is there a Bambu Studio app for iPad?',
        'No. Bambu Studio is a desktop application for Windows, macOS and '
        + 'Linux, and there is no iPadOS version on the App Store. Bambu Lab '
        + 'publishes Bambu Handy for iOS and iPadOS, but Handy sends and '
        + 'monitors prints -- it does not prepare a model.'],
      ['Can I run Bambu Studio on an iPad some other way?',
        'Only by remote-controlling a computer that is already running it, '
        + 'through a remote desktop app. There is no way to run it on the iPad '
        + 'itself.'],
      ['Can I prepare a model for a Bambu printer without any computer?',
        'Yes. Handoff3D runs in Safari on an iPad and writes a print-ready '
        + 'Bambu project file into the Files app. Bambu Handy then sends it to '
        + 'the printer.'],
    ],
  },

  {
    slug: 'resize-a-model-on-ipad',
    title: 'How to resize an STL or 3MF on an iPad',
    description:
      'Scale a downloaded 3D model to the size you want on an iPad, in Safari, '
      + 'and save a print-ready file for a Bambu Lab printer. No app, no '
      + 'account, nothing uploaded.',
    h1: 'How to resize a model on an iPad',
    lede:
      'You can resize a downloaded model on an iPad without installing '
      + 'anything: open <a href="/">' + BRAND + '</a> in Safari, choose the '
      + 'file, and type the size you want in millimetres. It shows you the '
      + 'model at that size on your printer&#x27;s own bed and saves a '
      + 'print-ready file into Files. The whole thing happens in the browser '
      + 'tab -- your model is never uploaded.',
    sections: [
      ['Step by step', [
        '<ol>'
        + '<li><b>Get the file onto the iPad.</b> Downloading from MakerWorld, '
        + 'Printables or Thingiverse in Safari puts it in Files, under '
        + 'Downloads.</li>'
        + '<li><b>Open the page and tap Choose a model.</b> iOS offers Photo '
        + 'Library and Take Photo first -- you want <b>Choose File</b>, the '
        + 'third row down.</li>'
        + '<li><b>Pick your printer.</b> The bed drawn underneath the model '
        + 'changes to match, so you can see immediately whether the thing '
        + 'fits.</li>'
        + '<li><b>Set the size.</b> Type a measurement in millimetres, or drag '
        + 'the slider. Across, deep and tall are all shown, so you can size by '
        + 'whichever one matters -- the height of a figure, the width of a '
        + 'bracket, the diameter of a lid.</li>'
        + '<li><b>Save it.</b> Out comes a Bambu project file, and a page of '
        + 'instructions for getting it to the printer.</li>'
        + '</ol>',
      ]],
      ['Size by the measurement that matters, not by percent', [
        '<p>Most resizing goes wrong because it is done as a percentage. '
        + '&quot;Scale to 140%&quot; tells you nothing about whether the result '
        + 'fits the shelf. Here you give the real measurement, in millimetres, '
        + 'and the other two directions follow proportionally.</p>',
        '<p>One thing worth knowing if your model arrived tipped or lying on '
        + 'its side: the sizes are measured against the model as it will stand '
        + 'on the plate, not against however the file happened to be saved. So '
        + '&quot;tall&quot; is the height it will actually print at.</p>',
      ]],
      ['If it is too big for the bed', [
        '<p>Scaling down is not the only way out. A model larger than your bed '
        + 'can be cut up and spread over as many plates as it needs, then '
        + 'printed in pieces -- see <a href="/split-a-model-too-big-for-your-'
        + 'bed">when a model is too big for the bed</a>.</p>',
      ]],
      ['Which files it will open', [
        '<p>STL, 3MF, OBJ and PLY -- the four formats models are actually '
        + 'published in. A 3MF exported by Bambu Studio or OrcaSlicer opens '
        + 'fine.</p>',
      ]],
    ],
    faq: [
      ['How do I scale an STL on an iPad?',
        'Open Handoff3D in Safari, choose the STL from your Files app, and '
        + 'enter the size you want in millimetres. It writes a resized, '
        + 'print-ready file back into Files. Nothing is installed and the model '
        + 'is not uploaded.'],
      ['Can I resize a 3MF without a computer?',
        'Yes. 3MF is one of the four formats it reads, alongside STL, OBJ and '
        + 'PLY, and the file it writes back out is a Bambu project file.'],
      ['Does resizing in a browser lose quality?',
        'No. Scaling a model is arithmetic on its coordinates. The shape is '
        + 'described mathematically, so it comes out as the same shape at a '
        + 'different size, with nothing thrown away.'],
    ],
  },

  {
    slug: '3d-print-from-ipad',
    title: '3D printing from an iPad, with no computer at all',
    description:
      'The complete route from a downloaded model to a finished print using '
      + 'only an iPad or iPhone and a Bambu Lab printer. Free, no account, '
      + 'nothing uploaded.',
    h1: '3D printing from an iPad, with no computer',
    lede:
      'It is possible to go from a model you downloaded to an object on the '
      + 'plate using nothing but an iPad and a Bambu Lab printer. The step that '
      + 'used to need a desktop -- preparing the file -- now runs in Safari. '
      + 'The step after it, sending the file to the machine, has always been '
      + 'possible through Bambu Handy. This page is the whole route, end to '
      + 'end.',
    sections: [
      ['The three things that have to happen', [
        '<p><b>1. Find a model.</b> MakerWorld, Printables and Thingiverse all '
        + 'work in Safari. A download lands in Files, under Downloads.</p>',
        '<p><b>2. Prepare it.</b> Size it, stand it the right way up, and turn '
        + 'it into a file your printer understands. This is the part that used '
        + 'to need Bambu Studio on a desktop. <a href="/">' + BRAND + '</a> '
        + 'does it in the browser.</p>',
        '<p><b>3. Send it.</b> Bambu does not let other apps talk to your '
        + 'printer directly, so the file goes up to your own private page on '
        + 'MakerWorld, and Bambu Handy prints it from there. It is a handful of '
        + 'taps, once per model.</p>',
      ]],
      ['Why step three is clunky, and why it is not your fault', [
        '<p>There is no public way for a third-party app to hand a file to a '
        + 'Bambu printer. The machine takes work from Bambu&#x27;s own '
        + 'software, and from Bambu&#x27;s own cloud. So the file travels: iPad '
        + '&rarr; your private MakerWorld page &rarr; Bambu Handy &rarr; '
        + 'printer. Set the model to <b>Private</b> when you upload it and '
        + 'nobody else ever sees it.</p>',
        '<p>Every file comes with a page of these steps saved next to it, '
        + 'because there are several places to get lost and you will want it '
        + 'again next time. The steps are written out on '
        + '<a href="/how-to-print-from-an-ipad">getting the file to the '
        + 'printer</a>.</p>',
      ]],
      ['Does it work on an iPhone?', [
        '<p>Yes. It is the same page and the same route. An iPad is more '
        + 'comfortable for judging size on the bed, but nothing here needs the '
        + 'bigger screen.</p>',
      ]],
      ['What it costs', [
        '<p>Nothing. There is no account, no sign-in, and no upload of your '
        + 'model. Visits are counted anonymously, so it is possible to tell '
        + 'whether anybody is finding it; the model, its name and everything '
        + 'measured from it stay on your device.</p>',
      ]],
    ],
    faq: [
      ['Can you 3D print from an iPad without a computer?',
        'Yes, with a Bambu Lab printer. Prepare the file in Safari with '
        + 'Handoff3D, upload it as a private model on MakerWorld, and print it '
        + 'from the Bambu Handy app. No desktop computer is involved at any '
        + 'point.'],
      ['Does it work on an iPhone as well as an iPad?',
        'Yes. The same page works on an iPhone, and the steps are identical.'],
      ['Can Bambu Handy prepare a model on its own?',
        'No. Bambu Handy sends and monitors prints and browses MakerWorld. It '
        + 'cannot take a downloaded model and turn it into something printable '
        + '-- that is the gap this fills.'],
    ],
  },

  {
    slug: 'split-a-model-too-big-for-your-bed',
    title: 'Splitting a model too big for your printer bed, on an iPad',
    description:
      'Cut an oversized model into pieces and spread them across as many build '
      + 'plates as it takes, on an iPad, with no desktop slicer.',
    h1: 'When a model is too big for the bed',
    lede:
      'A model larger than your build plate does not have to be shrunk. It can '
      + 'be cut into pieces, laid out across as many plates as it needs, and '
      + 'printed in batches -- and <a href="/">' + BRAND + '</a> does that on '
      + 'an iPad, in Safari. You get one file containing every plate, in '
      + 'order.',
    sections: [
      ['What &quot;too big&quot; means on each machine', [
        '<p>Bed sizes vary more than people expect. An A1 mini gives you '
        + '180&nbsp;&times;&nbsp;180&nbsp;&times;&nbsp;180&nbsp;mm. A P1S, an '
        + 'X1 Carbon or an A1 gives you roughly 256&nbsp;mm in each direction. '
        + 'The H2D and H2S are larger again, around '
        + '350&nbsp;&times;&nbsp;320&nbsp;&times;&nbsp;325&nbsp;mm. Pick your '
        + 'printer and the plate drawn under the model is the real one, so it '
        + 'is obvious at a glance whether you have a problem.</p>',
      ]],
      ['Three ways out, in the order worth trying', [
        '<h3>Print it smaller</h3>'
        + '<p>Often the right answer, and always the least work. Type the size '
        + 'you want and look at it on the plate.</p>'
        + '<h3>Stand it differently</h3>'
        + '<p>A long, flat model that will not fit across the bed may fit '
        + 'diagonally, or standing on its end. The height of a Bambu bed is '
        + 'roughly the same as its width, so tipping something upright can buy '
        + 'a surprising amount of room.</p>'
        + '<h3>Cut it up</h3>'
        + '<p>For anything genuinely large this is the answer, and it is what '
        + 'people do for helmets, vases, statues and terrain. The pieces are '
        + 'laid out over several plates, and you print one plate at a time and '
        + 'glue the results.</p>',
      ]],
      ['Models that arrive already in pieces', [
        '<p>Many large models are published as a set of parts inside one file. '
        + 'Those are recognised as separate pieces, each stood up the best way '
        + 'for itself, and then arranged across plates -- so a file with '
        + 'fourteen parts in it does not become one impossible object.</p>',
      ]],
      ['Flattening a curved bottom', [
        '<p>A related problem: a model that was sculpted rather than designed '
        + 'often has no flat face to sit on, and printing it as it comes means '
        + 'either a large support structure or a poor first layer. You can take '
        + 'a slice off the bottom to give it a flat face to stand on, choosing '
        + 'how deep to cut and watching the footprint appear as you do.</p>',
      ]],
    ],
    faq: [
      ['How do I print something bigger than my Bambu printer bed?',
        'Cut it into pieces, print them across several plates, and glue them '
        + 'together. Handoff3D does the cutting and the plate layout on an '
        + 'iPad, in Safari, and writes one file containing every plate.'],
      ['How big is the Bambu P1S bed?',
        'About 256 x 256 x 250 mm. The A1 mini is 180 mm in each direction, and '
        + 'the H2D is roughly 350 x 320 x 325 mm.'],
      ['Can I split a model into parts on an iPad?',
        'Yes. It runs in the browser, so nothing is installed and the model is '
        + 'not uploaded anywhere.'],
    ],
  },

  {
    slug: 'print-an-ai-generated-model',
    title: 'How to print an AI-generated 3D model from an iPad',
    description:
      'Take a model produced by a text-to-3D tool and get it printed on a Bambu '
      + 'Lab printer using only an iPad -- including the three things generated '
      + 'models always get wrong.',
    h1: 'Printing an AI-generated model',
    lede:
      'Text-to-3D tools will hand you an STL or OBJ in a minute. Getting that '
      + 'onto a printer is the other half, and from an iPad it used to have no '
      + 'answer at all. <a href="/">' + BRAND + '</a> takes the file the '
      + 'generator gave you, sizes it, stands it up, gives it a flat bottom if '
      + 'it needs one, and writes a print-ready Bambu file -- in Safari, on the '
      + 'iPad.',
    sections: [
      ['The three things generated models get wrong', [
        '<h3>They have no size</h3>'
        + '<p>A generated model is usually a couple of units tall, or a couple '
        + 'of thousand, with no relationship to millimetres at all. Whatever it '
        + 'arrives as, type the height you actually want.</p>'
        + '<h3>They are rarely the right way up</h3>'
        + '<p>Generators do not think about which face touches the plate. Each '
        + 'piece is stood up in a way that will print, and you can turn it '
        + 'yourself if you disagree.</p>'
        + '<h3>They have no flat face</h3>'
        + '<p>This is the big one. A generated figure is a closed shape '
        + 'floating in space, touching the plate at a single point. Taking a '
        + 'slice off the bottom gives it something to stand on, and you choose '
        + 'how deep the cut goes while watching the footprint it produces.</p>',
      ]],
      ['Getting the file out of the generator and into Files', [
        '<p>Download it in Safari and it lands in Files, under Downloads. If '
        + 'the tool only offers GLB or GLTF, look for an STL or OBJ option -- '
        + 'those are what a printer wants, and most generators offer at least '
        + 'one of them.</p>',
      ]],
      ['What it will not fix', [
        '<p>Generated models are frequently hollow where they should be solid, '
        + 'or carry detail finer than a nozzle can lay down, or are made of '
        + 'surfaces that do not quite close up into a solid object. Sizing and '
        + 'standing up will not repair any of that. If a print fails in a way '
        + 'that looks like the model rather than the printer, the honest answer '
        + 'is usually to generate it again from a simpler prompt.</p>',
      ]],
    ],
    faq: [
      ['Can I 3D print an AI-generated model from an iPad?',
        'Yes. Download the STL or OBJ the generator produced, open Handoff3D in '
        + 'Safari, size it, flatten the bottom if it needs one, and save a '
        + 'print-ready Bambu file. Bambu Handy then sends it to the printer.'],
      ['Why will my AI-generated model not sit flat on the plate?',
        'Text-to-3D tools produce closed shapes floating in space, with no flat '
        + 'face anywhere on them. Cutting a thin slice off the bottom gives the '
        + 'model a flat footprint to stand on.'],
      ['What file should I export from an AI 3D generator?',
        'STL or OBJ. Both are read directly. GLB and GLTF are display formats, '
        + 'and most printing tools, this one included, do not take them.'],
    ],
  },

  {
    slug: 'how-to-print-from-an-ipad',
    title: 'Getting a file from your iPad to a Bambu printer',
    description:
      'The exact taps that move a prepared file from the Files app to a Bambu '
      + 'Lab printer, through MakerWorld and Bambu Handy, with no computer '
      + 'involved.',
    h1: 'Getting the file to the printer',
    lede:
      'Once you have a print-ready file on your iPad, this is how it reaches '
      + 'the machine. <b>It is clunky, and it is not you.</b> Bambu does not '
      + 'let other apps talk to your printer directly, so the file has to go up '
      + 'to your own private page first. It is a handful of taps, once per '
      + 'model, and no computer is involved.',
    sections: [
      ['The six steps', [
        '<ol>'
        + '<li><b>Get the file into Files.</b> iCloud Drive or On My iPad, '
        + 'either works. If it arrived by AirDrop or e-mail, tap Share and '
        + 'choose Save to Files.</li>'
        + '<li><b>Open makerworld.com in Safari</b> and sign in. You only have '
        + 'to sign in once -- it remembers you after that.</li>'
        + '<li><b>Tap Upload, then Choose file</b>, and pick the file you just '
        + 'saved.</li>'
        + '<li><b>Add a picture.</b> MakerWorld asks for a photo here and will '
        + 'not take a rendered one. Any real photo from your camera roll gets '
        + 'you through, and the model is private, so nobody else sees it.</li>'
        + '<li><b>Set it to Private, then Publish.</b> Any title at all will '
        + 'do. Private is the part that matters -- it keeps the model '
        + 'yours.</li>'
        + '<li><b>Open Bambu Handy and print it.</b> Tap your profile picture, '
        + 'top left, then 3D Models. Yours is at the top of the list. Pick your '
        + 'printer and your colour, and print.</li>'
        + '</ol>',
      ]],
      ['If you cannot find it in Handy', [
        '<p>There is a second route to the same place. Open the <b>Me</b> tab. '
        + 'There is a row of things like printing history and print queue -- '
        + '<b>slide that row to the right</b> until you see <b>My '
        + 'Creations</b>, and your model is in there.</p>',
      ]],
      ['Keep it private until you have printed it', [
        '<div class="card"><p>MakerWorld only lets a model be made public once '
        + 'you have printed it yourself and can show a photo of the real thing. '
        + 'Making one public without that photo breaks the terms you agreed to '
        + 'when you signed up. Leave it private -- nothing about printing it '
        + 'needs it to be public.</p></div>',
      ]],
      ['You are the one at the printer', [
        '<div class="card"><p>Nobody has printed your file before you. Whether '
        + 'the settings suit your machine is yours to check: stay with it for '
        + 'the first few minutes and stop the printer if anything does not look '
        + 'right. Any damage to your printer, or to anything else, is your '
        + 'responsibility and not this tool&#x27;s.</p></div>',
      ]],
    ],
    faq: [
      ['How do I send a file to a Bambu printer from an iPad?',
        'Upload it to MakerWorld as a private model in Safari, then open Bambu '
        + 'Handy, find it under your profile in 3D Models, and print it. There '
        + 'is no way for a third-party app to hand a file to the printer '
        + 'directly.'],
      ['Why do I have to upload to MakerWorld to print my own file?',
        'Bambu printers accept work from Bambu software and the Bambu cloud, '
        + 'and MakerWorld is the only route into that cloud from an iPad. '
        + 'Setting the model to Private means nobody else can see it.'],
      ['Can I keep the model private on MakerWorld and still print it?',
        'Yes. A private model prints exactly the same way. MakerWorld requires '
        + 'a photo of a real print before it will let you make one public at '
        + 'all.'],
    ],
  },
]

/** Short label for a page, used in the footer links between them. */
export const LABEL = {
  'bambu-studio-on-ipad': 'Bambu Studio on iPad',
  'resize-a-model-on-ipad': 'Resizing a model on an iPad',
  '3d-print-from-ipad': '3D printing from an iPad, with no computer',
  'split-a-model-too-big-for-your-bed': 'When a model is too big for the bed',
  'print-an-ai-generated-model': 'Printing an AI-generated model',
  'how-to-print-from-an-ipad': 'Getting the file to the printer',
}

/**
 * JSON-LD, two blocks per page. The FAQ is the one that earns its place -- it
 * is the shape an answer engine reads a question-and-answer off. The breadcrumb
 * is there so the page is understood as sitting under the app rather than
 * floating on its own.
 */
function jsonLd(page) {
  const faq = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: page.faq.map(([q, a]) => ({
      '@type': 'Question',
      name: q,
      acceptedAnswer: { '@type': 'Answer', text: a },
    })),
  }
  const crumbs = {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      { '@type': 'ListItem', position: 1, name: BRAND, item: SITE + '/' },
      {
        '@type': 'ListItem',
        position: 2,
        name: page.h1,
        item: SITE + '/' + page.slug,
      },
    ],
  }
  return [faq, crumbs]
    .map((o) => '<script type="application/ld+json">\n'
      + JSON.stringify(o, null, 2) + '\n</script>')
    .join('\n')
}

function faqBlock(page) {
  const items = page.faq
    .map(([q, a]) => '<h3>' + escape(q) + '</h3>\n<p>' + dashes(a) + '</p>')
    .join('\n')
  return '<h2>Common questions</h2>\n' + items
}

function footerLinks(page) {
  const others = PAGES.filter((p) => p.slug !== page.slug)
    .map((p) => '<li><a href="/' + p.slug + '">' + escape(LABEL[p.slug])
      + '</a></li>')
    .join('\n')
  return '<footer>\n<p><b>' + BRAND + '</b> is a free page that prepares 3D '
    + 'models for Bambu Lab printers on an iPad. Nothing is installed, and your '
    + 'model is not uploaded.</p>\n<ul>\n' + others + '\n</ul>\n</footer>'
}

/** One page, as a complete HTML file. */
export function renderPage(page) {
  const url = SITE + '/' + page.slug
  const body = page.sections
    .map(([heading, parts]) => '<h2>' + escape(heading) + '</h2>\n'
      + parts.map(dashes).join('\n'))
    .join('\n')

  return '<!doctype html>\n<html lang="en">\n<head>\n'
    + '<meta charset="utf-8">\n'
    + '<meta name="viewport" content="width=device-width, initial-scale=1, '
    + 'viewport-fit=cover">\n'
    + '<meta name="theme-color" content="#101215">\n'
    + '<title>' + escape(page.title) + '</title>\n'
    + '<meta name="description" content="' + escape(page.description) + '">\n'
    + '<link rel="canonical" href="' + url + '">\n'
    + '<link rel="icon" type="image/png" sizes="32x32" href="/icons/icon-32.png">\n'
    + '<meta property="og:type" content="article">\n'
    + '<meta property="og:site_name" content="' + BRAND + '">\n'
    + '<meta property="og:title" content="' + escape(page.title) + '">\n'
    + '<meta property="og:description" content="' + escape(page.description) + '">\n'
    + '<meta property="og:url" content="' + url + '">\n'
    + '<meta property="og:image" content="' + SITE + OG_IMAGE + '">\n'
    + '<meta name="twitter:card" content="summary">\n'
    + '<meta name="twitter:title" content="' + escape(page.title) + '">\n'
    + '<meta name="twitter:description" content="' + escape(page.description) + '">\n'
    + '<meta name="twitter:image" content="' + SITE + OG_IMAGE + '">\n'
    + jsonLd(page) + '\n'
    + '<style>' + CSS + '</style>\n'
    + '</head>\n<body>\n'
    + '<header><a class="home" href="/">&larr; <b>' + BRAND + '</b> &mdash; '
    + '3D print, no computer necessary</a></header>\n'
    + '<main>\n'
    + '<h1>' + escape(page.h1) + '</h1>\n'
    + '<p class="lede">' + dashes(page.lede) + '</p>\n'
    + '<a class="cta" href="/">Open ' + BRAND + '</a>\n'
    + '<p class="cta-sub">Free, no account, nothing installed. Works in Safari '
    + 'on an iPad or an iPhone.</p>\n'
    + body + '\n'
    + faqBlock(page) + '\n'
    + '<a class="cta" href="/">Open ' + BRAND + '</a>\n'
    + '</main>\n'
    + footerLinks(page) + '\n'
    + '</body>\n</html>\n'
}

/**
 * robots.txt. The default is allow, so naming the answer engines changes
 * nothing technically -- it is here because "are we blocking GPTBot" is a
 * question that gets asked, and a file that answers it in writing settles it.
 * The dashboard is behind a key and already carries its own noindex; it is
 * named here as well so it is never fetched in the first place.
 */
export function renderRobots() {
  const agents = [
    'GPTBot', 'OAI-SearchBot', 'ChatGPT-User', 'ClaudeBot', 'Claude-User',
    'anthropic-ai', 'PerplexityBot', 'Perplexity-User', 'Google-Extended',
    'Applebot-Extended', 'CCBot', 'Bingbot', 'meta-externalagent',
  ]
  return '# ' + BRAND + ' -- everything here is meant to be found.\n'
    + '# The answer engines are named explicitly so that "is this site\n'
    + '# blocking them" has a written answer rather than an assumed one.\n\n'
    + 'User-agent: *\n'
    + 'Allow: /\n'
    + 'Disallow: /dashboard\n'
    + 'Disallow: /dashboard.html\n\n'
    + agents.map((a) => 'User-agent: ' + a + '\nAllow: /\n').join('\n')
    + '\nSitemap: ' + SITE + '/sitemap.xml\n'
}

/** sitemap.xml. The app first, then the pages -- all of them real files. */
export function renderSitemap(today) {
  const urls = [{ loc: SITE + '/', priority: '1.0' }].concat(
    PAGES.map((p) => ({ loc: SITE + '/' + p.slug, priority: '0.8' })))
  const body = urls
    .map(({ loc, priority }) => '  <url>\n'
      + '    <loc>' + loc + '</loc>\n'
      + '    <lastmod>' + today + '</lastmod>\n'
      + '    <changefreq>monthly</changefreq>\n'
      + '    <priority>' + priority + '</priority>\n'
      + '  </url>')
    .join('\n')
  return '<?xml version="1.0" encoding="UTF-8"?>\n'
    + '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
    + body + '\n</urlset>\n'
}
